import crypto from "node:crypto";
import { query, queryOne, execute } from "./db.server";
import { generateBase32Secret } from "./totp.server";

// ---------------------------------------------------------------------------
// Typed data-access layer (server-only). All queries are parameterized.
// Repositories are intentionally small, async functions over the pg helpers.
// ---------------------------------------------------------------------------

export function newId(prefix = ""): string {
  const id = crypto.randomBytes(16).toString("hex");
  return prefix ? `${prefix}_${id}` : id;
}

const now = () => Date.now();

/**
 * Referral reward rate: the referrer earns this fraction of every paid invoice
 * generated by users they referred. 0.15 = 15%.
 */
export const REFERRAL_RATE = 0.15;

/** Length of a referral code (alphanumeric). */
const REFERRAL_CODE_LENGTH = 6;

/** Human-friendly, unambiguous referral code (no 0/O/1/I). */
function genReferralCode(): string {
  const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let out = "";
  const bytes = crypto.randomBytes(REFERRAL_CODE_LENGTH);
  for (let i = 0; i < REFERRAL_CODE_LENGTH; i++) out += alphabet[bytes[i] % alphabet.length];
  return out;
}

// --- Types ------------------------------------------------------------------

export interface UserRow {
  id: string;
  username: string;
  global_name: string | null;
  mc_username: string | null;
  avatar_url: string | null;
  email: string | null;
  is_admin: number;
  is_banned: number;
  is_beta: number;
  is_owner: number;
  discord_joined: number;
  admin_otp_secret: string | null;
  referral_code: string | null;
  referred_by: string | null;
  credit_usd: number;
  extra_bot_slots: number;
  created_at: number;
  last_login_at: number;
}

export interface PlanRow {
  id: string;
  name: string;
  description: string;
  price_usd: number;
  interval: string;
  max_bots: number;
  max_proxies: number;
  bot_hours: number;  // -1 = unlimited
  features: string;
  is_active: number;
  is_hidden: number;  // 1 = not shown in purchase UI (admin plan)
  is_trial: number;   // 1 = free trial plan
  sort_order: number;
}

export interface SubscriptionRow {
  id: string;
  user_id: string;
  plan_id: string;
  status: "pending" | "active" | "expired" | "canceled";
  started_at: number | null;
  expires_at: number | null;
  created_at: number;
}

export interface PaymentRow {
  id: string;
  user_id: string;
  plan_id: string | null;
  plugin_id: string | null;
  kind: "subscription" | "plugin" | "slot";
  subscription_id: string | null;
  coin: string;
  amount_usd: number;
  credit_applied: number;
  slot_qty: number;
  amount_crypto: string | null;
  received_crypto: string | null;
  pay_address: string | null;
  status: "waiting" | "confirming" | "paid" | "expired" | "failed";
  txid: string | null;
  notified_at: number | null;
  created_at: number;
  updated_at: number;
}

export interface NotificationRow {
  id: string;
  user_id: string;
  type: string;
  title: string;
  body: string | null;
  read: number;
  created_at: number;
}

export interface UserSettingsRow {
  user_id: string;
  notify_payments: number;
  notify_bots: number;
  notify_announcements: number;
  theme: string;
  updated_at: number;
}

export interface ProxyRow {
  id: string;
  host: string;
  port: number;
  username: string | null;
  password: string | null;
  protocol: "http" | "socks5";
  label: string | null;
  assigned_user_id: string | null;
  created_at: number;
}

// --- Users ------------------------------------------------------------------

export const usersRepo = {
  async upsertOnLogin(input: {
  id: string;
  username: string;
  globalName: string | null;
  avatarUrl: string | null;
  email: string | null;  // ✅ Aggiungi email
}): Promise<UserRow> {
  const existing = await queryOne("SELECT * FROM users WHERE id = ?", [input.id]) as UserRow | undefined;

  if (existing) {
    await execute(`UPDATE users SET username = ?, global_name = ?, avatar_url = ?, email = ?, last_login_at = ?
       WHERE id = ?`, [input.username,
      input.globalName,
      input.avatarUrl,
      input.email,  // ✅ Aggiungi email
      now(),
      input.id]);
  } else {
    await execute(`INSERT INTO users (id, username, global_name, avatar_url, email, referral_code, created_at, last_login_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?)`, [input.id,
      input.username,
      input.globalName,
      input.avatarUrl,
      input.email,  // ✅ Aggiungi email
      genReferralCode(),
      now(),
      now()]);
    // Default settings row.
    await execute(`INSERT INTO user_settings (user_id, updated_at) VALUES (?, ?) ON CONFLICT (user_id) DO NOTHING`, [input.id, now()]);
  }

  // Backfill a referral code for accounts created before the referral program.
  await usersRepo.ensureReferralCode(input.id);

  return await queryOne("SELECT * FROM users WHERE id = ?", [input.id]) as UserRow;
},

  async byId(id: string): Promise<UserRow | undefined> {
    return await queryOne("SELECT * FROM users WHERE id = ?", [id]) as
      | UserRow
      | undefined;
  },

  /**
   * In this app the user's primary key IS their Discord ID (set at OAuth login),
   * so looking up "by discord id" is the same as looking up by id.
   */
  async byDiscordId(discordId: string): Promise<UserRow | undefined> {
    return usersRepo.byId(discordId);
  },

  async byUsername(username: string): Promise<UserRow | undefined> {
    return await queryOne("SELECT * FROM users WHERE username = ? ORDER BY created_at ASC LIMIT 1", [username]) as UserRow | undefined;
  },

  async markDiscordJoined(id: string): Promise<void> {
    await execute("UPDATE users SET discord_joined = 1 WHERE id = ?", [id]);
  },

  async setAdmin(id: string, isAdmin: boolean): Promise<void> {
    await execute("UPDATE users SET is_admin = ? WHERE id = ?", [isAdmin ? 1 : 0, id]);
  },

  async setBanned(id: string, banned: boolean): Promise<void> {
    await execute("UPDATE users SET is_banned = ? WHERE id = ?", [banned ? 1 : 0, id]);
  },

  async setBeta(id: string, beta: boolean): Promise<void> {
    await execute("UPDATE users SET is_beta = ? WHERE id = ?", [beta ? 1 : 0, id]);
  },

  /** Ensure the user has a unique referral code, generating one if missing. */
  async ensureReferralCode(id: string): Promise<string> {
    const row = (await queryOne("SELECT referral_code FROM users WHERE id = ?", [id])) as
      | { referral_code: string | null }
      | undefined;
    if (row?.referral_code) return row.referral_code;
    // Retry a few times in the (very unlikely) event of a code collision.
    for (let i = 0; i < 5; i++) {
      const code = genReferralCode();
      try {
        await execute("UPDATE users SET referral_code = ? WHERE id = ?", [code, id]);
        return code;
      } catch {
        /* unique violation — try again */
      }
    }
    throw new Error("Could not generate a unique referral code");
  },

  async byReferralCode(code: string): Promise<UserRow | undefined> {
    return (await queryOne("SELECT * FROM users WHERE referral_code = ?", [code])) as
      | UserRow
      | undefined;
  },

  /**
   * Link a new user to their referrer. No-op if the user was already referred,
   * is referring themselves, or the code is invalid.
   */
  async setReferredByCode(userId: string, code: string): Promise<void> {
    const me = await usersRepo.byId(userId);
    if (!me || me.referred_by) return;
    const referrer = await usersRepo.byReferralCode(code);
    if (!referrer || referrer.id === userId) return;
    await execute("UPDATE users SET referred_by = ? WHERE id = ?", [referrer.id, userId]);
  },

  /** Add spendable credit to a user's balance (USD). */
  async addCredit(id: string, amountUsd: number): Promise<void> {
    if (amountUsd === 0) return;
    await execute("UPDATE users SET credit_usd = credit_usd + ? WHERE id = ?", [amountUsd, id]);
  },

  async creditBalance(id: string): Promise<number> {
    const row = (await queryOne("SELECT credit_usd FROM users WHERE id = ?", [id])) as
      | { credit_usd: number }
      | undefined;
    return row?.credit_usd ?? 0;
  },


  /** Read the number of lifetime extra bot slots a user owns. */
  async extraBotSlots(id: string): Promise<number> {
    const row = (await queryOne("SELECT extra_bot_slots FROM users WHERE id = ?", [id])) as
      | { extra_bot_slots: number }
      | undefined;
    return row?.extra_bot_slots ?? 0;
  },

  /** Grant additional lifetime bot slots to a user. */
  async addBotSlots(id: string, qty: number): Promise<void> {
    if (qty === 0) return;
    await execute("UPDATE users SET extra_bot_slots = extra_bot_slots + ? WHERE id = ?", [qty, id]);
  },

  /** Persist the Minecraft username for a user (used so the bot can DM on payment). */
  async setMcUsername(id: string, mcUsername: string): Promise<void> {
    await execute("UPDATE users SET mc_username = ? WHERE id = ?", [mcUsername, id]);
  },

  /** Users referred by `id`, newest first. */
  async referredUsers(id: string): Promise<UserRow[]> {
    return (await query(
      "SELECT * FROM users WHERE referred_by = ? ORDER BY created_at DESC",
      [id],
    )) as UserRow[];
  },

  /**
   * Return the admin's TOTP secret, generating and persisting one on first use.
   * Used to gate critical admin actions behind the website's rotating OTP.
   */
  async getOrCreateAdminOtpSecret(id: string): Promise<string> {
    const row = await queryOne(
      "SELECT admin_otp_secret FROM users WHERE id = ?",
      [id],
    ) as { admin_otp_secret: string | null } | undefined;
    if (row?.admin_otp_secret) return row.admin_otp_secret;
    const secret = generateBase32Secret();
    await execute("UPDATE users SET admin_otp_secret = ? WHERE id = ?", [secret, id]);
    return secret;
  },

  async all(): Promise<UserRow[]> {
    return await query("SELECT * FROM users ORDER BY created_at DESC", []) as UserRow[];
  },

  async count(): Promise<number> {
    return (
      await queryOne("SELECT COUNT(*) AS c FROM users", []) as { c: number }
    ).c;
  },

  /**
   * Permanently delete ALL data associated with a user.
   * Deletes from all related tables first (foreign key safety), then the user.
   * This is irreversible — use with extreme caution.
   */
  async hardDelete(userId: string): Promise<void> {
    // Delete in dependency order (child tables before parent)
    await execute("DELETE FROM bot_hour_balances WHERE user_id = ?", [userId]);
    await execute("DELETE FROM bot_runs WHERE user_id = ?", [userId]);
    await execute("DELETE FROM bots WHERE user_id = ?", [userId]);
    await execute("DELETE FROM payments WHERE user_id = ?", [userId]);
    await execute("DELETE FROM subscriptions WHERE user_id = ?", [userId]);
    await execute("DELETE FROM proxies WHERE assigned_user_id = ?", [userId]);
    await execute("DELETE FROM warns WHERE user_id = ?", [userId]);
    await execute("DELETE FROM notes WHERE user_id = ?", [userId]);
    await execute("DELETE FROM tickets WHERE user_id = ?", [userId]);
    await execute("DELETE FROM notifications WHERE user_id = ?", [userId]);
    await execute("DELETE FROM trial_redemptions WHERE user_id = ?", [userId]);
    await execute("DELETE FROM user_settings WHERE user_id = ?", [userId]);
    await execute("DELETE FROM global_chat_messages WHERE user_id = ?", [userId]);
    await execute("DELETE FROM reviews WHERE user_id = ?", [userId]);
    await execute("DELETE FROM dm_queue WHERE discord_id = ?", [userId]);
    await execute("DELETE FROM user_ips WHERE user_id = ?", [userId]);
    await execute("DELETE FROM admin_audit WHERE actor_id = ? OR target_id = ?", [userId, userId]);
    await execute("DELETE FROM users WHERE id = ?", [userId]);
  },
};

// --- Referral credits -------------------------------------------------------

export interface ReferralCreditRow {
  id: string;
  user_id: string;        // the referrer who earned the credit
  source_user_id: string; // the referred friend who paid
  payment_id: string;
  amount_usd: number;
  created_at: number;
}

export const referralCreditsRepo = {
  /**
   * Award referral credit for a paid invoice. Idempotent on payment_id, so
   * re-processing the same payment never double-credits. Also bumps the
   * referrer's spendable balance. Returns the credited amount (0 if skipped).
   */
  async award(input: {
    referrerId: string;
    sourceUserId: string;
    paymentId: string;
    amountUsd: number;
  }): Promise<number> {
    if (input.amountUsd <= 0) return 0;
    const res = await execute(
      `INSERT INTO referral_credits (id, user_id, source_user_id, payment_id, amount_usd, created_at)
       VALUES (?, ?, ?, ?, ?, ?)
       ON CONFLICT (payment_id) DO NOTHING`,
      [newId("rc"), input.referrerId, input.sourceUserId, input.paymentId, input.amountUsd, now()],
    );
    if (res.rowCount === 0) return 0; // already credited
    await usersRepo.addCredit(input.referrerId, input.amountUsd);
    return input.amountUsd;
  },

  async totalEarned(userId: string): Promise<number> {
    const row = (await queryOne(
      "SELECT COALESCE(SUM(amount_usd), 0) AS s FROM referral_credits WHERE user_id = ?",
      [userId],
    )) as { s: number };
    return row.s;
  },

  async historyForUser(userId: string, limit = 20): Promise<ReferralCreditRow[]> {
    return (await query(
      "SELECT * FROM referral_credits WHERE user_id = ? ORDER BY created_at DESC LIMIT ?",
      [userId, limit],
    )) as ReferralCreditRow[];
  },
};

/**
 * Reward the referrer (if any) of the buyer who just completed `payment`.
 * Idempotent on payment id, so it is safe to call from both the crypto webhook
 * and the credit-only instant-paid path. Amount is REFERRAL_RATE of the money
 * actually received (amount_usd, i.e. after any credit was applied).
 */
export async function grantReferralReward(payment: {
  id: string;
  user_id: string;
  amount_usd: number;
}): Promise<void> {
  const buyer = await usersRepo.byId(payment.user_id);
  if (!buyer?.referred_by) return;
  const reward = Math.round(payment.amount_usd * REFERRAL_RATE * 100) / 100;
  if (reward <= 0) return;
  const credited = await referralCreditsRepo.award({
    referrerId: buyer.referred_by,
    sourceUserId: buyer.id,
    paymentId: payment.id,
    amountUsd: reward,
  });
  if (credited <= 0) return; // already credited
  const settings = await settingsRepo.get(buyer.referred_by);
  if (settings.notify_payments !== 0) {
    await notificationsRepo.create({
      userId: buyer.referred_by,
      type: "success",
      title: "Referral reward earned",
      body: `You earned $${credited.toFixed(2)} in account credit from a referral purchase.`,
    });
  }
}

// --- Plans ------------------------------------------------------------------

export const plansRepo = {
  /** Returns all visible (non-hidden) active plans — safe to send to clients */
  async allActive(): Promise<PlanRow[]> {
    return await query("SELECT * FROM plans WHERE is_active = 1 AND is_hidden = 0 ORDER BY sort_order ASC", []) as PlanRow[];
  },
  /** All plans including hidden ones — admin use only */
  async allIncludingHidden(): Promise<PlanRow[]> {
    return await query("SELECT * FROM plans WHERE is_active = 1 ORDER BY sort_order ASC", []) as PlanRow[];
  },
  async byId(id: string): Promise<PlanRow | undefined> {
    return await queryOne("SELECT * FROM plans WHERE id = ?", [id]) as
      | PlanRow
      | undefined;
  },
  /** All active plans (alias used by the bot) — excludes hidden via filter at call site */
  async all(): Promise<PlanRow[]> {
    return await query("SELECT * FROM plans WHERE is_active = 1 ORDER BY sort_order ASC", []) as PlanRow[];
  },
};

// --- Trial Redemptions ------------------------------------------------------

export interface TrialRedemptionRow {
  id: string;
  user_id: string;
  ip: string;
  discord_role_added: number;
  redeemed_at: number;
}

export const trialRepo = {
  async hasRedeemedByUser(userId: string): Promise<boolean> {
    const row = await queryOne("SELECT id FROM trial_redemptions WHERE user_id = ?", [userId]);
    return !!row;
  },

  async hasRedeemedByIp(ip: string): Promise<boolean> {
    const row = await queryOne("SELECT id FROM trial_redemptions WHERE ip = ?", [ip]);
    return !!row;
  },

  async record(userId: string, ip: string): Promise<void> {
    await execute(`INSERT INTO trial_redemptions (id, user_id, ip, discord_role_added, redeemed_at)
         VALUES (?, ?, ?, 0, ?) ON CONFLICT (user_id) DO NOTHING`, [newId("trl"), userId, ip, Date.now()]);
  },
};

// --- Subscriptions ----------------------------------------------------------

export const subscriptionsRepo = {
  async create(userId: string, planId: string): Promise<SubscriptionRow> {
    const id = newId("sub");
    await execute(`INSERT INTO subscriptions (id, user_id, plan_id, status, created_at)
       VALUES (?, ?, ?, 'pending', ?)`, [id, userId, planId, now()]);
    return await queryOne("SELECT * FROM subscriptions WHERE id = ?", [id]) as SubscriptionRow;
  },

  async activate(id: string, durationMs: number): Promise<void> {
    const start = now();
    await execute(`UPDATE subscriptions SET status = 'active', started_at = ?, expires_at = ? WHERE id = ?`, [start, start + durationMs, id]);
  },

  async activeForUser(userId: string): Promise<SubscriptionRow | undefined> {
    return await queryOne(`SELECT * FROM subscriptions
         WHERE user_id = ? AND status = 'active' AND (expires_at IS NULL OR expires_at > ?)
         ORDER BY created_at DESC LIMIT 1`, [userId, now()]) as SubscriptionRow | undefined;
  },

  async listForUser(userId: string): Promise<SubscriptionRow[]> {
    return await query("SELECT * FROM subscriptions WHERE user_id = ? ORDER BY created_at DESC", [userId]) as SubscriptionRow[];
  },

  async activeCount(): Promise<number> {
    return (
      await queryOne(`SELECT COUNT(*) AS c FROM subscriptions WHERE status = 'active' AND (expires_at IS NULL OR expires_at > ?)`, [now()]) as { c: number }
    ).c;
  },

  /** Set (or replace) the active plan for a user. Cancels any existing active subs first. */
  async setForUser(userId: string, planId: string, durationDays = 30): Promise<SubscriptionRow> {
    await execute(`UPDATE subscriptions SET status = 'canceled' WHERE user_id = ? AND status = 'active'`, [userId]);
    const id = newId("sub");
    const start = now();
    const expires = start + durationDays * 24 * 60 * 60 * 1000;
    await execute(`INSERT INTO subscriptions (id, user_id, plan_id, status, started_at, expires_at, created_at)
       VALUES (?, ?, ?, 'active', ?, ?, ?)`, [id, userId, planId, start, expires, start]);
    return await queryOne("SELECT * FROM subscriptions WHERE id = ?", [id]) as SubscriptionRow;
  },

  /** Revoke (cancel) all active subscriptions for a user. */
  async revokeForUser(userId: string): Promise<void> {
    await execute(`UPDATE subscriptions SET status = 'canceled' WHERE user_id = ? AND status = 'active'`, [userId]);
  },
};

// --- Payments ---------------------------------------------------------------

export const paymentsRepo = {
  async create(input: {
    id: string;
    userId: string;
    planId?: string | null;
    pluginId?: string | null;
    kind?: "subscription" | "plugin" | "slot" | "bot_hours";
    subscriptionId?: string | null;
    coin: string;
    amountUsd: number;
    creditApplied?: number;
    slotQty?: number;
  }): Promise<PaymentRow> {
    const t = now();
    await execute(`INSERT INTO payments (id, user_id, plan_id, plugin_id, kind, subscription_id, coin, amount_usd, credit_applied, slot_qty, status, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'waiting', ?, ?)`, [
      input.id,
      input.userId,
      input.planId ?? null,
      input.pluginId ?? null,
      input.kind ?? "subscription",
      input.subscriptionId ?? null,
      input.coin,
      input.amountUsd,
      input.creditApplied ?? 0,
      input.slotQty ?? 0,
      t,
      t,
    ]);
    return await queryOne("SELECT * FROM payments WHERE id = ?", [input.id]) as
      PaymentRow;
  },

  async setAddress(id: string, address: string, amountCrypto: string): Promise<void> {
    await execute("UPDATE payments SET pay_address = ?, amount_crypto = ?, updated_at = ? WHERE id = ?", [address, amountCrypto, now(), id]);
  },

  async updateStatus(
    id: string,
    status: PaymentRow["status"],
    extra?: { receivedCrypto?: string; txid?: string },
  ): Promise<void> {
    await execute(`UPDATE payments SET status = ?,
           received_crypto = COALESCE(?, received_crypto),
           txid = COALESCE(?, txid),
           updated_at = ?
         WHERE id = ?`, [status, extra?.receivedCrypto ?? null, extra?.txid ?? null, now(), id]);
  },

  async byId(id: string): Promise<PaymentRow | undefined> {
    return await queryOne("SELECT * FROM payments WHERE id = ?", [id]) as
      | PaymentRow
      | undefined;
  },

  async byIdForUser(id: string, userId: string): Promise<PaymentRow | undefined> {
    return await queryOne("SELECT * FROM payments WHERE id = ? AND user_id = ?", [id, userId]) as PaymentRow | undefined;
  },

  async pendingForUser(userId: string): Promise<PaymentRow | undefined> {
    return await queryOne(`SELECT * FROM payments WHERE user_id = ? AND status IN ('waiting', 'confirming')
         ORDER BY created_at DESC LIMIT 1`, [userId]) as PaymentRow | undefined;
  },

  async listForUser(userId: string): Promise<PaymentRow[]> {
    return await query("SELECT * FROM payments WHERE user_id = ? ORDER BY created_at DESC", [userId]) as PaymentRow[];
  },

  async recent(limit = 50): Promise<PaymentRow[]> {
    return await query("SELECT * FROM payments ORDER BY created_at DESC LIMIT ?", [limit]) as PaymentRow[];
  },

  /** Paid invoices the bot hasn't DM'd the player about yet. Bot polls this. */
  async pendingBotNotification(limit = 20): Promise<PaymentRow[]> {
    return await query(
      `SELECT * FROM payments WHERE status = 'paid' AND notified_at IS NULL ORDER BY updated_at ASC LIMIT ?`,
      [limit],
    ) as PaymentRow[];
  },

  /** Mark a paid invoice as notified so the bot won't spam the player. */
  async markNotified(id: string): Promise<void> {
    await execute("UPDATE payments SET notified_at = ? WHERE id = ? AND notified_at IS NULL", [now(), id]);
  },

  async totalRevenueUsd(): Promise<number> {
    return (
      (await queryOne("SELECT COALESCE(SUM(amount_usd), 0) AS s FROM payments WHERE status = 'paid'", []) as { s: number }).s
    );
  },

  async cancelWaiting(id: string, userId: string): Promise<boolean> {
    // Only cancel if status is 'waiting' (not yet confirmed/paid)
    const result = await execute(`UPDATE payments SET status = 'failed', updated_at = ?
         WHERE id = ? AND user_id = ? AND status = 'waiting'`, [now(), id, userId]);
    if (result.rowCount > 0) await paymentsRepo.refundCredit(id);
    return result.rowCount > 0;
  },

  async adminCancel(id: string): Promise<boolean> {
    const result = await execute(`UPDATE payments SET status = 'failed', updated_at = ?
         WHERE id = ? AND status IN ('waiting', 'confirming')`, [now(), id]);
    if (result.rowCount > 0) await paymentsRepo.refundCredit(id);
    return result.rowCount > 0;
  },

  /**
   * Return any spent referral credit to the user's balance and zero it on the
   * payment, so cancelling an invoice never burns the buyer's credit. Idempotent.
   */
  async refundCredit(id: string): Promise<void> {
    const p = (await queryOne(
      "SELECT user_id, credit_applied FROM payments WHERE id = ?",
      [id],
    )) as { user_id: string; credit_applied: number } | undefined;
    if (!p || !p.credit_applied) return;
    await usersRepo.addCredit(p.user_id, p.credit_applied);
    await execute("UPDATE payments SET credit_applied = 0 WHERE id = ?", [id]);
  },
};

// --- Notifications ----------------------------------------------------------

export const notificationsRepo = {
  async create(input: {
    userId: string;
    type: string;
    title: string;
    body?: string;
  }): Promise<NotificationRow> {
    const id = newId("ntf");
    await execute(`INSERT INTO notifications (id, user_id, type, title, body, created_at)
       VALUES (?, ?, ?, ?, ?, ?)`, [id, input.userId, input.type, input.title, input.body ?? null, now()]);
    return await queryOne("SELECT * FROM notifications WHERE id = ?", [id]) as NotificationRow;
  },

  async listForUser(userId: string, limit = 50): Promise<NotificationRow[]> {
    return await query("SELECT * FROM notifications WHERE user_id = ? ORDER BY created_at DESC LIMIT ?", [userId, limit]) as NotificationRow[];
  },

  async unreadCount(userId: string): Promise<number> {
    return (
      await queryOne("SELECT COUNT(*) AS c FROM notifications WHERE user_id = ? AND read = 0", [userId]) as { c: number }
    ).c;
  },

  async markAllRead(userId: string): Promise<void> {
    await execute("UPDATE notifications SET read = 1 WHERE user_id = ?", [userId]);
  },

  async markRead(id: string, userId: string): Promise<void> {
    await execute("UPDATE notifications SET read = 1 WHERE id = ? AND user_id = ?", [id, userId]);
  },
};

// --- Settings ---------------------------------------------------------------

export const settingsRepo = {
  async get(userId: string): Promise<UserSettingsRow> {
    let row = await queryOne("SELECT * FROM user_settings WHERE user_id = ?", [userId]) as UserSettingsRow | undefined;
    if (!row) {
      await execute("INSERT INTO user_settings (user_id, updated_at) VALUES (?, ?) ON CONFLICT (user_id) DO NOTHING", [userId, now()]);
      row = await queryOne("SELECT * FROM user_settings WHERE user_id = ?", [userId]) as UserSettingsRow;
    }
    return row;
  },

  async update(
    userId: string,
    patch: Partial<{
      notify_payments: number;
      notify_bots: number;
      notify_announcements: number;
      theme: string;
    }>,
  ): Promise<UserSettingsRow> {
    const current = await settingsRepo.get(userId); // ensure exists
    const merged = {
      notify_payments: patch.notify_payments ?? current.notify_payments,
      notify_bots: patch.notify_bots ?? current.notify_bots,
      notify_announcements:
        patch.notify_announcements ?? current.notify_announcements,
      theme: patch.theme ?? current.theme,
    };
    await execute(`UPDATE user_settings SET notify_payments = ?, notify_bots = ?,
         notify_announcements = ?, theme = ?, updated_at = ? WHERE user_id = ?`, [merged.notify_payments,
      merged.notify_bots,
      merged.notify_announcements,
      merged.theme,
      now(),
      userId]);
    return await settingsRepo.get(userId);
  },
};

// --- Banned IPs -------------------------------------------------------------

export interface BannedIpRow {
  ip: string;
  reason: string | null;
  banned_by: string;
  created_at: number;
}

export const bannedIpsRepo = {
  async ban(ip: string, bannedBy: string, reason?: string): Promise<void> {
    await execute(`INSERT INTO banned_ips (ip, reason, banned_by, created_at)
         VALUES (?, ?, ?, ?)
         ON CONFLICT (ip) DO UPDATE SET reason = EXCLUDED.reason, banned_by = EXCLUDED.banned_by, created_at = EXCLUDED.created_at`, [ip, reason ?? null, bannedBy, Date.now()]);
  },

  async unban(ip: string): Promise<void> {
    await execute("DELETE FROM banned_ips WHERE ip = ?", [ip]);
  },

  /** Object-arg alias used by the bot */
  async add(input: { ip: string; reason?: string; bannedBy: string }): Promise<void> {
    bannedIpsRepo.ban(input.ip, input.bannedBy, input.reason);
  },

  /** Alias used by the bot */
  async remove(ip: string): Promise<void> {
    bannedIpsRepo.unban(ip);
  },

  async isBanned(ip: string): Promise<boolean> {
    const row = await queryOne("SELECT ip FROM banned_ips WHERE ip = ?", [ip]);
    return !!row;
  },

  async all(): Promise<BannedIpRow[]> {
    return await query("SELECT * FROM banned_ips ORDER BY created_at DESC", []) as BannedIpRow[];
  },
};

// --- User IP history --------------------------------------------------------

export interface UserIpRow {
  user_id: string;
  ip: string;
  first_seen: number;
  last_seen: number;
  hits: number;
}

export const userIpsRepo = {
  /** Record an IP seen for a user (upsert: bumps last_seen and hit count). */
  async record(userId: string, ip: string): Promise<void> {
    if (!ip) return;
    const ts = Date.now();
    await execute(
      `INSERT INTO user_ips (user_id, ip, first_seen, last_seen, hits)
         VALUES (?, ?, ?, ?, 1)
         ON CONFLICT (user_id, ip)
         DO UPDATE SET last_seen = EXCLUDED.last_seen, hits = user_ips.hits + 1`,
      [userId, ip, ts, ts],
    );
  },

  /** All IPs recorded for a user, most recently seen first. */
  async forUser(userId: string): Promise<UserIpRow[]> {
    return (await query(
      "SELECT * FROM user_ips WHERE user_id = ? ORDER BY last_seen DESC",
      [userId],
    )) as UserIpRow[];
  },
};

// --- Proxies ----------------------------------------------------------------

export const proxiesRepo = {
  async all(): Promise<ProxyRow[]> {
    return await query("SELECT * FROM proxies ORDER BY created_at DESC", []) as ProxyRow[];
  },

  async forUser(userId: string): Promise<ProxyRow[]> {
    return await query("SELECT * FROM proxies WHERE assigned_user_id = ? ORDER BY created_at DESC", [userId]) as ProxyRow[];
  },

  /**
   * Proxies a bot owned by `userId` is allowed to draw from: the shared pool
   * (admin-added, unassigned) plus the user's own custom proxies.
   */
  async poolForUser(userId: string): Promise<ProxyRow[]> {
    return await query(
      "SELECT * FROM proxies WHERE assigned_user_id IS NULL OR assigned_user_id = ? ORDER BY created_at DESC",
      [userId],
    ) as ProxyRow[];
  },

  /** System/shared proxies only (admin-added, not assigned to any user). */
  async systemPool(): Promise<ProxyRow[]> {
    return await query(
      "SELECT * FROM proxies WHERE assigned_user_id IS NULL ORDER BY created_at DESC",
      [],
    ) as ProxyRow[];
  },

  async create(input: {
    host: string;
    port: number;
    username?: string | null;
    password?: string | null;
    protocol: "http" | "socks5";
    label?: string | null;
    assignedUserId?: string | null;
  }): Promise<ProxyRow> {
    const id = newId("prx");
    await execute(`INSERT INTO proxies (id, host, port, username, password, protocol, label, assigned_user_id, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`, [id,
      input.host,
      input.port,
      input.username ?? null,
      input.password ?? null,
      input.protocol,
      input.label ?? null,
      input.assignedUserId ?? null,
      now()]);
    return await queryOne("SELECT * FROM proxies WHERE id = ?", [id]) as ProxyRow;
  },

  async assign(id: string, userId: string | null): Promise<void> {
    await execute("UPDATE proxies SET assigned_user_id = ? WHERE id = ?", [userId, id]);
  },

  async delete(id: string): Promise<void> {
    await execute("DELETE FROM proxies WHERE id = ?", [id]);
  },

  /** Alias used by the bot (maps `type` -> protocol) */
  async add(input: { host: string; port: number; type?: "http" | "socks5" }): Promise<ProxyRow> {
    return proxiesRepo.create({
      host: input.host,
      port: input.port,
      protocol: input.type ?? "http",
    });
  },

  /** Alias used by the bot */
  async remove(id: string): Promise<void> {
    proxiesRepo.delete(id);
  },

  async count(): Promise<number> {
    return (await queryOne("SELECT COUNT(*) AS c FROM proxies", []) as { c: number }).c;
  },
};

// --- Reviews -----------------------------------------------------------------

export interface ReviewRow {
  id: string;
  user_id: string;
  discord_id: string;
  discord_tag: string;
  stars: number;
  feedback: string;
  status: "pending" | "approved" | "rejected";
  channel_msg_id: string | null;
  created_at: number;
}

export const reviewsRepo = {
  async create(input: {
    userId: string;
    discordId: string;
    discordTag: string;
    stars: number;
    feedback: string;
  }): Promise<ReviewRow> {
    const id = newId("rev");
    await execute(
      `INSERT INTO reviews (id, user_id, discord_id, discord_tag, stars, feedback, status, created_at)
         VALUES (?, ?, ?, ?, ?, ?, 'pending', ?)`,
      [id, input.userId, input.discordId, input.discordTag, input.stars, input.feedback, now()],
    );
    return await queryOne("SELECT * FROM reviews WHERE id = ?", [id]) as ReviewRow;
  },

  async approved(): Promise<ReviewRow[]> {
    return await query(
      "SELECT * FROM reviews WHERE status = 'approved' ORDER BY created_at DESC",
      [],
    ) as ReviewRow[];
  },

  async byUser(userId: string): Promise<ReviewRow[]> {
    return await query(
      "SELECT * FROM reviews WHERE user_id = ? ORDER BY created_at DESC",
      [userId],
    ) as ReviewRow[];
  },

  async pending(): Promise<ReviewRow[]> {
    return await query(
      "SELECT * FROM reviews WHERE status = 'pending' ORDER BY created_at ASC",
      [],
    ) as ReviewRow[];
  },

  async setStatus(id: string, status: ReviewRow["status"], channelMsgId?: string): Promise<ReviewRow | undefined> {
    if (channelMsgId !== undefined) {
      await execute("UPDATE reviews SET status = ?, channel_msg_id = ? WHERE id = ?", [
        status,
        channelMsgId,
        id,
      ]);
    } else {
      await execute("UPDATE reviews SET status = ? WHERE id = ?", [status, id]);
    }
    return await queryOne("SELECT * FROM reviews WHERE id = ?", [id]) as ReviewRow | undefined;
  },

  async all(): Promise<ReviewRow[]> {
    return await query("SELECT * FROM reviews ORDER BY created_at DESC", []) as ReviewRow[];
  },
};

// --- Suggestions ------------------------------------------------------------

export interface SuggestionRow {
  id: string;
  channel_id: string;
  message_id: string | null;
  thread_id: string | null;
  author_id: string;
  author_tag: string;
  content: string;
  status: "open" | "approved" | "denied" | "implemented";
  created_at: number;
}

export const suggestionsRepo = {
  async create(input: {
    channelId: string;
    authorId: string;
    authorTag: string;
    content: string;
  }): Promise<SuggestionRow> {
    const id = newId("sug");
    await execute(
      `INSERT INTO suggestions (id, channel_id, author_id, author_tag, content, status, created_at)
         VALUES (?, ?, ?, ?, ?, 'open', ?)`,
      [id, input.channelId, input.authorId, input.authorTag, input.content, now()],
    );
    return (await queryOne("SELECT * FROM suggestions WHERE id = ?", [id])) as SuggestionRow;
  },

  async byId(id: string): Promise<SuggestionRow | undefined> {
    return (await queryOne("SELECT * FROM suggestions WHERE id = ?", [id])) as
      | SuggestionRow
      | undefined;
  },

  async setMessage(id: string, messageId: string, threadId: string | null): Promise<void> {
    await execute("UPDATE suggestions SET message_id = ?, thread_id = ? WHERE id = ?", [
      messageId,
      threadId,
      id,
    ]);
  },

  async setStatus(id: string, status: SuggestionRow["status"]): Promise<void> {
    await execute("UPDATE suggestions SET status = ? WHERE id = ?", [status, id]);
  },

  /**
   * Cast (or toggle) a vote. Clicking the same direction again removes the
   * vote; clicking the opposite direction switches it. Returns fresh counts.
   */
  async vote(
    suggestionId: string,
    userId: string,
    vote: 1 | -1,
  ): Promise<{ up: number; down: number }> {
    const existing = (await queryOne(
      "SELECT vote FROM suggestion_votes WHERE suggestion_id = ? AND user_id = ?",
      [suggestionId, userId],
    )) as { vote: number } | undefined;

    if (existing && existing.vote === vote) {
      await execute("DELETE FROM suggestion_votes WHERE suggestion_id = ? AND user_id = ?", [
        suggestionId,
        userId,
      ]);
    } else {
      await execute(
        `INSERT INTO suggestion_votes (suggestion_id, user_id, vote, created_at)
           VALUES (?, ?, ?, ?)
           ON CONFLICT (suggestion_id, user_id)
           DO UPDATE SET vote = EXCLUDED.vote, created_at = EXCLUDED.created_at`,
        [suggestionId, userId, vote, now()],
      );
    }
    return suggestionsRepo.counts(suggestionId);
  },

  async counts(suggestionId: string): Promise<{ up: number; down: number }> {
    const row = (await queryOne(
      `SELECT
         COALESCE(SUM(CASE WHEN vote = 1 THEN 1 ELSE 0 END), 0) AS up,
         COALESCE(SUM(CASE WHEN vote = -1 THEN 1 ELSE 0 END), 0) AS down
       FROM suggestion_votes WHERE suggestion_id = ?`,
      [suggestionId],
    )) as { up: number; down: number } | undefined;
    return { up: Number(row?.up ?? 0), down: Number(row?.down ?? 0) };
  },
};

// --- Tickets ----------------------------------------------------------------

export interface TicketRow {
  id: string;
  user_id: string;
  discord_user_id: string;
  discord_user_tag: string;
  channel_id: string | null;
  subject: string;
  category: string;
  status: "open" | "closed" | "in_progress";
  priority: "low" | "normal" | "high" | "urgent";
  source: "discord" | "web";
  closed_by: string | null;
  closed_at: number | null;
  claimed_by: string | null;
  created_at: number;
  updated_at: number;
}

export interface TicketMessageRow {
  id: string;
  ticket_id: string;
  author_id: string;
  author_tag: string;
  content: string;
  is_staff: number;
  created_at: number;
}

export const ticketsRepo = {
  async create(input: {
    userId: string;
    discordUserId: string;
    discordUserTag: string;
    channelId?: string | null;
    subject: string;
    category?: string;
    priority?: TicketRow["priority"];
    source?: TicketRow["source"];
  }): Promise<TicketRow> {
    const id = newId("tkt");
    const t = now();
    await execute(`INSERT INTO tickets (id, user_id, discord_user_id, discord_user_tag, channel_id, subject, category, status, priority, source, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, 'open', ?, ?, ?, ?)`, [id,
      input.userId,
      input.discordUserId,
      input.discordUserTag,
      input.channelId ?? null,
      input.subject,
      input.category ?? "general",
      input.priority ?? "normal",
      input.source ?? "discord",
      t,
      t]);
    return await queryOne("SELECT * FROM tickets WHERE id = ?", [id]) as TicketRow;
  },

  /** Create a web ticket (Pro/Enterprise dashboard) */
  async createWeb(input: {
    userId: string;
    discordUserId: string;
    discordUserTag: string;
    subject: string;
    category?: string;
    priority?: TicketRow["priority"];
  }): Promise<TicketRow> {
    return ticketsRepo.create({ ...input, source: "web", channelId: null });
  },

  async bySource(userId: string, source: TicketRow["source"]): Promise<TicketRow[]> {
    return await query("SELECT * FROM tickets WHERE user_id = ? AND source = ? ORDER BY created_at DESC", [userId, source]) as TicketRow[];
  },

  async byId(id: string): Promise<TicketRow | undefined> {
    return await queryOne("SELECT * FROM tickets WHERE id = ?", [id]) as TicketRow | undefined;
  },

  async byChannel(channelId: string): Promise<TicketRow | undefined> {
    return await queryOne("SELECT * FROM tickets WHERE channel_id = ?", [channelId]) as TicketRow | undefined;
  },

  async byUser(userId: string): Promise<TicketRow[]> {
    return await query("SELECT * FROM tickets WHERE user_id = ? ORDER BY created_at DESC", [userId]) as TicketRow[];
  },

  async all(status?: TicketRow["status"]): Promise<TicketRow[]> {
    if (status) {
      return await query("SELECT * FROM tickets WHERE status = ? ORDER BY created_at DESC", [status]) as TicketRow[];
    }
    return await query("SELECT * FROM tickets ORDER BY created_at DESC", []) as TicketRow[];
  },

  async setChannel(id: string, channelId: string): Promise<void> {
    await execute("UPDATE tickets SET channel_id = ?, updated_at = ? WHERE id = ?", [channelId, now(), id]);
  },

  async setStatus(id: string, status: TicketRow["status"], closedBy?: string): Promise<void> {
    const t = now();
    if (status === "closed") {
      await execute("UPDATE tickets SET status = ?, closed_by = ?, closed_at = ?, updated_at = ? WHERE id = ?", [status, closedBy ?? null, t, t, id]);
    } else {
      await execute("UPDATE tickets SET status = ?, updated_at = ? WHERE id = ?", [status, t, id]);
    }
  },

  async claim(id: string, staffId: string): Promise<void> {
    await execute("UPDATE tickets SET claimed_by = ?, status = 'in_progress', updated_at = ? WHERE id = ?", [staffId, now(), id]);
  },

  async setPriority(id: string, priority: TicketRow["priority"]): Promise<void> {
    await execute("UPDATE tickets SET priority = ?, updated_at = ? WHERE id = ?", [priority, now(), id]);
  },

  async count(status?: TicketRow["status"]): Promise<number> {
    if (status) {
      return (await queryOne("SELECT COUNT(*) AS c FROM tickets WHERE status = ?", [status]) as { c: number }).c;
    }
    return (await queryOne("SELECT COUNT(*) AS c FROM tickets", []) as { c: number }).c;
  },

  async addMessage(input: {
    ticketId: string;
    authorId: string;
    authorTag: string;
    content: string;
    isStaff?: boolean;
  }): Promise<TicketMessageRow> {
    const id = newId("tmsg");
    await execute(`INSERT INTO ticket_messages (id, ticket_id, author_id, author_tag, content, is_staff, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?)`, [id, input.ticketId, input.authorId, input.authorTag, input.content, input.isStaff ? 1 : 0, now()]);
    return await queryOne("SELECT * FROM ticket_messages WHERE id = ?", [id]) as TicketMessageRow;
  },

  async messages(ticketId: string): Promise<TicketMessageRow[]> {
    return await query("SELECT * FROM ticket_messages WHERE ticket_id = ? ORDER BY created_at ASC", [ticketId]) as TicketMessageRow[];
  },
};

// --- User Warns -------------------------------------------------------------

export interface UserWarnRow {
  id: string;
  user_id: string;
  actor_id: string;
  reason: string;
  created_at: number;
}

export const warnsRepo = {
  async add(input: { userId: string; issuedBy: string; reason: string }): Promise<UserWarnRow> {
    const id = newId("wrn");
    await execute(`INSERT INTO user_warns (id, user_id, actor_id, reason, created_at) VALUES (?, ?, ?, ?, ?)`, [id, input.userId, input.issuedBy, input.reason, now()]);
    return await queryOne("SELECT * FROM user_warns WHERE id = ?", [id]) as UserWarnRow;
  },

  async byUser(userId: string): Promise<UserWarnRow[]> {
    return await query("SELECT * FROM user_warns WHERE user_id = ? ORDER BY created_at DESC", [userId]) as UserWarnRow[];
  },

  async forUser(userId: string): Promise<UserWarnRow[]> {
    return warnsRepo.byUser(userId);
  },

  async remove(id: string): Promise<void> {
    await execute("DELETE FROM user_warns WHERE id = ?", [id]);
  },

  async count(userId: string): Promise<number> {
    return (await queryOne("SELECT COUNT(*) AS c FROM user_warns WHERE user_id = ?", [userId]) as { c: number }).c;
  },
};

// --- User Notes -------------------------------------------------------------

export interface UserNoteRow {
  id: string;
  user_id: string;
  actor_id: string;
  content: string;
  created_at: number;
}

export const notesRepo = {
  async add(input: { userId: string; authorId: string; content: string }): Promise<UserNoteRow> {
    const id = newId("nte");
    await execute(`INSERT INTO user_notes (id, user_id, actor_id, content, created_at) VALUES (?, ?, ?, ?, ?)`, [id, input.userId, input.authorId, input.content, now()]);
    return await queryOne("SELECT * FROM user_notes WHERE id = ?", [id]) as UserNoteRow;
  },

  async byUser(userId: string): Promise<UserNoteRow[]> {
    return await query("SELECT * FROM user_notes WHERE user_id = ? ORDER BY created_at DESC", [userId]) as UserNoteRow[];
  },

  async forUser(userId: string): Promise<UserNoteRow[]> {
    return notesRepo.byUser(userId);
  },

  async remove(id: string): Promise<void> {
    await execute("DELETE FROM user_notes WHERE id = ?", [id]);
  },
};

// --- Admin audit log --------------------------------------------------------

export interface AuditLogRow {
  id: string;
  actor_id: string;
  action: string;
  target_id: string | null;
  detail: string | null;
  created_at: number;
  is_owner: number;
}

export const auditRepo = {
  async log(input: { actorId: string; action: string; targetId?: string; detail?: string; isOwner?: boolean }): Promise<void> {
    const id = newId("aud");
    await execute(
      `INSERT INTO admin_audit (id, actor_id, action, target_id, detail, created_at, is_owner) VALUES (?, ?, ?, ?, ?, ?, ?)`,
      [id, input.actorId, input.action, input.targetId ?? null, input.detail ?? null, now(), input.isOwner ? 1 : 0],
    );
  },

  async recent(limit = 100): Promise<AuditLogRow[]> {
    return await query(
      `SELECT * FROM admin_audit ORDER BY created_at DESC LIMIT ?`,
      [limit],
    ) as AuditLogRow[];
  },
};

// --- DM queue (web -> Discord bot bridge for premium ticket notifications) --

export interface DmQueueRow {
  id: string;
  discord_id: string;
  title: string;
  body: string;
  url: string | null;
  status: "pending" | "sent" | "failed";
  created_at: number;
  sent_at: number | null;
}

export const dmQueueRepo = {
  async enqueue(input: { discordId: string; title: string; body: string; url?: string }): Promise<DmQueueRow> {
    const id = newId("dm");
    await execute(`INSERT INTO dm_queue (id, discord_id, title, body, url, status, created_at)
       VALUES (?, ?, ?, ?, ?, 'pending', ?)`, [id, input.discordId, input.title, input.body, input.url ?? null, now()]);
    return await queryOne("SELECT * FROM dm_queue WHERE id = ?", [id]) as DmQueueRow;
  },

  async pending(limit = 25): Promise<DmQueueRow[]> {
    return await query("SELECT * FROM dm_queue WHERE status = 'pending' ORDER BY created_at ASC LIMIT ?", [limit]) as DmQueueRow[];
  },

  async markSent(id: string): Promise<void> {
    await execute("UPDATE dm_queue SET status = 'sent', sent_at = ? WHERE id = ?", [now(), id]);
  },

  async markFailed(id: string): Promise<void> {
    await execute("UPDATE dm_queue SET status = 'failed', sent_at = ? WHERE id = ?", [now(), id]);
  },
};

// --- Bot settings (global key-value, used by the Discord bot) ---------------
export const botSettingsRepo = {
  async get(key: string): Promise<string | null> {
    const row = await queryOne("SELECT value FROM bot_settings WHERE key = ?", [key]) as { value: string | null } | undefined;
    return row?.value ?? null;
  },

  async set(key: string, value: string): Promise<void> {
    await execute(`INSERT INTO bot_settings (key, value, updated_at) VALUES (?, ?, ?)
         ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at`, [key, value, now()]);
  },
};

// --- AI chat per-user toggle (persistent, survives bot restarts) ------------
export const aiChatRepo = {
  /** All Discord user IDs that currently have AI replies enabled. */
  async enabledUserIds(): Promise<string[]> {
    const rows = await query("SELECT user_id FROM ai_chat_users WHERE enabled = 1", []) as { user_id: string }[];
    return rows.map((r) => r.user_id);
  },

  async isEnabled(userId: string): Promise<boolean> {
    const row = await queryOne("SELECT enabled FROM ai_chat_users WHERE user_id = ?", [userId]) as { enabled: number } | undefined;
    return (row?.enabled ?? 0) === 1;
  },

  async setEnabled(userId: string, enabled: boolean): Promise<void> {
    await execute(`INSERT INTO ai_chat_users (user_id, enabled, updated_at) VALUES (?, ?, ?)
         ON CONFLICT(user_id) DO UPDATE SET enabled = excluded.enabled, updated_at = excluded.updated_at`,
      [userId, enabled ? 1 : 0, now()]);
  },
};

// --- Anti-VPN verdict cache (persistent, shared across instances) -----------
export interface VpnCacheRow {
  vpn: number;
  proxy: number;
  tor: number;
  hosting: number;
  expires_at: number;
}

export const vpnCacheRepo = {
  /** Returns the cached verdict for an IP, or null if missing/expired. */
  async get(ip: string): Promise<VpnCacheRow | null> {
    const row = (await queryOne(
      "SELECT vpn, proxy, tor, hosting, expires_at FROM vpn_cache WHERE ip = ?",
      [ip],
    )) as VpnCacheRow | undefined;
    if (!row) return null;
    if (row.expires_at <= now()) {
      await execute("DELETE FROM vpn_cache WHERE ip = ?", [ip]);
      return null;
    }
    return row;
  },

  /** Upserts a verdict with an absolute expiry timestamp (ms). */
  async set(
    ip: string,
    v: { vpn: boolean; proxy: boolean; tor: boolean; hosting: boolean },
    expiresAt: number,
  ): Promise<void> {
    await execute(
      `INSERT INTO vpn_cache (ip, vpn, proxy, tor, hosting, expires_at)
       VALUES (?, ?, ?, ?, ?, ?)
       ON CONFLICT(ip) DO UPDATE SET
         vpn = excluded.vpn, proxy = excluded.proxy, tor = excluded.tor,
         hosting = excluded.hosting, expires_at = excluded.expires_at`,
      [ip, v.vpn ? 1 : 0, v.proxy ? 1 : 0, v.tor ? 1 : 0, v.hosting ? 1 : 0, expiresAt],
    );
  },
};

// --- Plugins ----------------------------------------------------------------

export interface PluginPurchaseRow {
  id: string;
  user_id: string;
  plugin_id: string;
  amount_usd: number;
  payment_id: string | null;
  created_at: number;
}

export interface PluginConfigRow {
  id: string;
  user_id: string;
  plugin_id: string;
  config: string; // JSON blob
  updated_at: number;
}

export interface PluginRunRow {
  id: string;
  user_id: string;
  plugin_id: string;
  config_snapshot: string; // JSON blob
  status: "pending" | "starting" | "running" | "stopped" | "error";
  container_id: string | null;
  error: string | null;
  created_at: number;
  updated_at: number;
  stopped_at: number | null;
}

export interface CaptchaRow {
  id: string;
  run_id: string;
  sitekey: string;
  rqdata: string | null;
  service: string;
  status: "pending" | "solved" | "cancelled";
  solution: string | null;
  created_at: number;
  updated_at: number;
}

export interface OutboxRow {
  id: string;
  run_id: string;
  target_id: string;
  content: string;
  status: "pending" | "sent";
  created_at: number;
  updated_at: number;
}

export const pluginsRepo = {
  // --- Purchases ---
  async isPurchased(userId: string, pluginId: string): Promise<boolean> {
    const row = await queryOne("SELECT id FROM plugin_purchases WHERE user_id = ? AND plugin_id = ?", [userId, pluginId]);
    return !!row;
  },

  async purchasedIds(userId: string): Promise<string[]> {
    const rows = await query("SELECT plugin_id FROM plugin_purchases WHERE user_id = ?", [userId]) as { plugin_id: string }[];
    return rows.map((r) => r.plugin_id);
  },

  async recordPurchase(input: {
    userId: string;
    pluginId: string;
    amountUsd?: number;
    paymentId?: string | null;
  }): Promise<PluginPurchaseRow> {
    const id = newId("plgp");
    await execute(`INSERT INTO plugin_purchases (id, user_id, plugin_id, amount_usd, payment_id, created_at)
       VALUES (?, ?, ?, ?, ?, ?)
       ON CONFLICT(user_id, plugin_id) DO NOTHING`, [id, input.userId, input.pluginId, input.amountUsd ?? 0, input.paymentId ?? null, now()]);
    return await queryOne("SELECT * FROM plugin_purchases WHERE user_id = ? AND plugin_id = ?", [input.userId, input.pluginId]) as PluginPurchaseRow;
  },

  // --- Config ---
  async getConfig(userId: string, pluginId: string): Promise<PluginConfigRow | undefined> {
    return await queryOne("SELECT * FROM plugin_configs WHERE user_id = ? AND plugin_id = ?", [userId, pluginId]) as PluginConfigRow | undefined;
  },

  async saveConfig(userId: string, pluginId: string, configJson: string): Promise<PluginConfigRow> {
    const id = newId("plgc");
    await execute(`INSERT INTO plugin_configs (id, user_id, plugin_id, config, updated_at)
       VALUES (?, ?, ?, ?, ?)
       ON CONFLICT(user_id, plugin_id) DO UPDATE SET
         config = excluded.config,
         updated_at = excluded.updated_at`, [id, userId, pluginId, configJson, now()]);
    return await queryOne("SELECT * FROM plugin_configs WHERE user_id = ? AND plugin_id = ?", [userId, pluginId]) as PluginConfigRow;
  },

  // --- Runs (Docker orchestration TBD) ---
  async createRun(input: {
    userId: string;
    pluginId: string;
    configSnapshot: string;
  }): Promise<PluginRunRow> {
    const id = newId("plgr");
    const t = now();
    await execute(`INSERT INTO plugin_runs (id, user_id, plugin_id, config_snapshot, status, created_at, updated_at)
       VALUES (?, ?, ?, ?, 'pending', ?, ?)`, [id, input.userId, input.pluginId, input.configSnapshot, t, t]);
    return await queryOne("SELECT * FROM plugin_runs WHERE id = ?", [id]) as PluginRunRow;
  },

  async runsForUser(userId: string, pluginId?: string): Promise<PluginRunRow[]> {
    if (pluginId) {
      return await query("SELECT * FROM plugin_runs WHERE user_id = ? AND plugin_id = ? ORDER BY created_at DESC", [userId, pluginId]) as PluginRunRow[];
    }
    return await query("SELECT * FROM plugin_runs WHERE user_id = ? ORDER BY created_at DESC", [userId]) as PluginRunRow[];
  },

  async activeRun(userId: string, pluginId: string): Promise<PluginRunRow | undefined> {
    return await queryOne(`SELECT * FROM plugin_runs
         WHERE user_id = ? AND plugin_id = ? AND status IN ('pending', 'starting', 'running')
         ORDER BY created_at DESC LIMIT 1`, [userId, pluginId]) as PluginRunRow | undefined;
  },

  /**
   * Most recent run for a plugin regardless of status. Used so the UI can keep
   * showing "stopped"/"error" after a run ends, instead of snapping back to
   * "idle" the moment the run leaves the active set.
   */
  async latestRun(userId: string, pluginId: string): Promise<PluginRunRow | undefined> {
    return await queryOne(`SELECT * FROM plugin_runs
         WHERE user_id = ? AND plugin_id = ?
         ORDER BY created_at DESC LIMIT 1`, [userId, pluginId]) as PluginRunRow | undefined;
  },

  async setRunStatus(
    id: string,
    status: PluginRunRow["status"],
    extra?: { containerId?: string; error?: string },
  ): Promise<void> {
    const t = now();
    const stoppedAt = status === "stopped" || status === "error" ? t : null;
    await execute(`UPDATE plugin_runs SET status = ?,
           container_id = COALESCE(?, container_id),
           error = COALESCE(?, error),
           updated_at = ?,
           stopped_at = COALESCE(?, stopped_at)
         WHERE id = ?`, [status, extra?.containerId ?? null, extra?.error ?? null, t, stoppedAt, id]);
  },

  async runByIdForUser(id: string, userId: string): Promise<PluginRunRow | undefined> {
    return await queryOne("SELECT * FROM plugin_runs WHERE id = ? AND user_id = ?", [id, userId]) as PluginRunRow | undefined;
  },

  /** Run lookup without a user scope — server/webhook use only. */
  async runById(id: string): Promise<PluginRunRow | undefined> {
    return await queryOne("SELECT * FROM plugin_runs WHERE id = ?", [id]) as PluginRunRow | undefined;
  },

  /** Run matched by its Docker container id — used to reconcile container state. */
  async runByContainerId(containerId: string): Promise<PluginRunRow | undefined> {
    return await queryOne("SELECT * FROM plugin_runs WHERE container_id = ?", [containerId]) as PluginRunRow | undefined;
  },

  /** All runs the orchestrator still considers live. */
  async activeRuns(): Promise<PluginRunRow[]> {
    return await query(`SELECT * FROM plugin_runs
         WHERE status IN ('pending', 'starting', 'running')
         ORDER BY created_at DESC`, []) as PluginRunRow[];
  },

  /** Most recent runs across all users — admin listing. */
  async allRuns(limit = 200): Promise<PluginRunRow[]> {
    return await query("SELECT * FROM plugin_runs ORDER BY created_at DESC LIMIT ?", [limit]) as PluginRunRow[];
  },

  // --- Live console logs ----------------------------------------------------

  /** Append a batch of structured log lines pushed by a run's container. */
  async appendRunLogs(
    runId: string,
    lines: { ts: string; level: string; msg: string }[],
  ): Promise<void> {
    if (lines.length === 0) return;
    const t = now();
    // Single multi-row INSERT keeps the endpoint fast even for big batches.
    const placeholders: string[] = [];
    const params: unknown[] = [];
    for (const ln of lines) {
      placeholders.push("(?, ?, ?, ?, ?)");
      params.push(runId, ln.ts ?? "", ln.level ?? "INFO", ln.msg ?? "", t);
    }
    await execute(
      `INSERT INTO plugin_run_logs (run_id, ts, level, msg, created_at) VALUES ${placeholders.join(", ")}`,
      params,
    );
  },

  /**
   * Fetch log lines for a run after a given autoincrement id (incremental
   * polling). Pass afterId = 0 to fetch from the start.
   */
  async runLogsAfter(
    runId: string,
    afterId: number,
    limit = 500,
  ): Promise<{ id: number; ts: string; level: string; msg: string }[]> {
    return await query(
      `SELECT id, ts, level, msg FROM plugin_run_logs
         WHERE run_id = ? AND id > ?
         ORDER BY id ASC LIMIT ?`,
      [runId, afterId, limit],
    ) as { id: number; ts: string; level: string; msg: string }[];
  },

  /** Drop a run's logs (called when its container is removed). */
  async clearRunLogs(runId: string): Promise<void> {
    await execute("DELETE FROM plugin_run_logs WHERE run_id = ?", [runId]);
  },

  // --- Live DM feed (Discord-style panel) -----------------------------------

  /** Append structured DM/relationship events pushed by a run's container. */
  async appendRunEvents(
    runId: string,
    events: { kind: string; author: string; authorId: string; content: string; ts: string }[],
  ): Promise<void> {
    if (events.length === 0) return;
    const t = now();
    const placeholders: string[] = [];
    const params: unknown[] = [];
    for (const ev of events) {
      placeholders.push("(?, ?, ?, ?, ?, ?, ?)");
      params.push(
        runId,
        ev.kind ?? "incoming",
        ev.author ?? "",
        ev.authorId ?? "",
        ev.content ?? "",
        ev.ts ?? "",
        t,
      );
    }
    await execute(
      `INSERT INTO plugin_run_events (run_id, kind, author, author_id, content, ts, created_at) VALUES ${placeholders.join(", ")}`,
      params,
    );
  },

  /** Incremental fetch of DM events for a run after a given autoincrement id. */
  async runEventsAfter(
    runId: string,
    afterId: number,
    limit = 300,
  ): Promise<{ id: number; kind: string; author: string; author_id: string; content: string; ts: string }[]> {
    return await query(
      `SELECT id, kind, author, author_id, content, ts FROM plugin_run_events
         WHERE run_id = ? AND id > ?
         ORDER BY id ASC LIMIT ?`,
      [runId, afterId, limit],
    ) as { id: number; kind: string; author: string; author_id: string; content: string; ts: string }[];
  },

  async clearRunEvents(runId: string): Promise<void> {
    await execute("DELETE FROM plugin_run_events WHERE run_id = ?", [runId]);
  },

  // --- Captcha challenges (manual solve from the dashboard) -----------------

  /** Register a captcha challenge raised by a container. */
  async createCaptcha(input: {
    runId: string;
    sitekey: string;
    rqdata?: string | null;
    service?: string;
  }): Promise<CaptchaRow> {
    const t = now();
    const id = newId("cap");
    await execute(
      `INSERT INTO plugin_captchas (id, run_id, sitekey, rqdata, service, status, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, 'pending', ?, ?)`,
      [id, input.runId, input.sitekey, input.rqdata ?? null, input.service ?? "hcaptcha", t, t],
    );
    return (await this.captchaById(id))!;
  },

  async captchaById(id: string): Promise<CaptchaRow | undefined> {
    return await queryOne("SELECT * FROM plugin_captchas WHERE id = ?", [id]) as CaptchaRow | undefined;
  },

  /** Latest still-pending captcha for a run (drives the solver modal). */
  async pendingCaptcha(runId: string): Promise<CaptchaRow | undefined> {
    return await queryOne(
      `SELECT * FROM plugin_captchas WHERE run_id = ? AND status = 'pending'
         ORDER BY created_at DESC LIMIT 1`,
      [runId],
    ) as CaptchaRow | undefined;
  },

  /** Store the user-provided token and mark the challenge solved. */
  async solveCaptcha(id: string, solution: string): Promise<void> {
    await execute(
      "UPDATE plugin_captchas SET status = 'solved', solution = ?, updated_at = ? WHERE id = ?",
      [solution, now(), id],
    );
  },

  async cancelCaptcha(id: string): Promise<void> {
    await execute(
      "UPDATE plugin_captchas SET status = 'cancelled', updated_at = ? WHERE id = ? AND status = 'pending'",
      [now(), id],
    );
  },

  // --- Outbox: manual replies queued from the dashboard ---------------------

  /** Queue a manual reply for a run's container to deliver to a Discord user. */
  async queueOutgoing(input: {
    runId: string;
    targetId: string;
    content: string;
  }): Promise<OutboxRow> {
    const t = now();
    const id = newId("out");
    await execute(
      `INSERT INTO plugin_outbox (id, run_id, target_id, content, status, created_at, updated_at)
         VALUES (?, ?, ?, ?, 'pending', ?, ?)`,
      [id, input.runId, input.targetId, input.content, t, t],
    );
    return (await queryOne("SELECT * FROM plugin_outbox WHERE id = ?", [id])) as OutboxRow;
  },

  /** Pending manual replies a container should send (claimed via markOutgoingSent). */
  async pendingOutgoing(runId: string, limit = 50): Promise<OutboxRow[]> {
    return (await query(
      `SELECT * FROM plugin_outbox WHERE run_id = ? AND status = 'pending'
         ORDER BY id ASC LIMIT ?`,
      [runId, limit],
    )) as OutboxRow[];
  },

  async markOutgoingSent(ids: string[]): Promise<void> {
    if (ids.length === 0) return;
    const placeholders = ids.map(() => "?").join(", ");
    await execute(
      `UPDATE plugin_outbox SET status = 'sent', updated_at = ? WHERE id IN (${placeholders})`,
      [now(), ...ids],
    );
  },

  async clearOutbox(runId: string): Promise<void> {
    await execute("DELETE FROM plugin_outbox WHERE run_id = ?", [runId]);
  },
};

// --- Bots -------------------------------------------------------------------

export interface BotRow {
  id: string;
  user_id: string;
  name: string;
  mc_username: string;
  server_host: string;
  server_port: number;
  mc_version: string;
  auth_mode: "offline" | "microsoft" | "ssid";
  access_token: string | null;
  ssid: string | null;
  uuid: string | null;
  auth_expires_at: number | null;
  proxy: string | null;
  message: string | null;
  reply: string | null;
  reply_actions: string | null;
  trigger_keyword: string | null;
  webhook_url: string | null;
  message_interval: number | null;
  reply_delay: number | null;
  reply_cooldown: number | null;
  afk_interval: number | null;
  reconnect_delay: number | null;
  inactivity_timeout: number | null;
  created_at: number;
  updated_at: number;
}

export interface BotRunRow {
  id: string;
  bot_id: string;
  user_id: string;
  status: "pending" | "starting" | "running" | "stopped" | "error";
  container_id: string | null;
  error: string | null;
  created_at: number;
  updated_at: number;
  stopped_at: number | null;
}

// --- Bot reply-action presets ----------------------------------------------

export interface BotPresetRow {
  id: string;
  owner_id: string | null;
  name: string;
  actions: string; // JSON array of command templates
  is_global: number;
  server_host: string | null;
  server_port: number | null;
  mc_version: string | null;
  created_at: number;
  updated_at: number;
}

export const presetsRepo = {
  /** Presets a user can see: global ones + their own. */
  async forUser(userId: string): Promise<BotPresetRow[]> {
    return (await query(
      `SELECT * FROM bot_presets
         WHERE is_global = 1 OR owner_id = ?
         ORDER BY is_global DESC, name ASC`,
      [userId],
    )) as BotPresetRow[];
  },

  /** Global presets only (admin-managed). */
  async globals(): Promise<BotPresetRow[]> {
    return (await query(
      "SELECT * FROM bot_presets WHERE is_global = 1 ORDER BY name ASC",
      [],
    )) as BotPresetRow[];
  },

  async byId(id: string): Promise<BotPresetRow | undefined> {
    return (await queryOne("SELECT * FROM bot_presets WHERE id = ?", [id])) as
      | BotPresetRow
      | undefined;
  },

  async create(input: {
    ownerId: string | null;
    name: string;
    actions: string[];
    isGlobal?: boolean;
    serverHost?: string | null;
    serverPort?: number | null;
    mcVersion?: string | null;
  }): Promise<BotPresetRow> {
    const id = newId("preset");
    const t = now();
    await execute(
      `INSERT INTO bot_presets (id, owner_id, name, actions, is_global, server_host, server_port, mc_version, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        id,
        input.isGlobal ? null : input.ownerId,
        input.name,
        JSON.stringify(input.actions),
        input.isGlobal ? 1 : 0,
        input.serverHost ?? null,
        input.serverPort ?? null,
        input.mcVersion ?? null,
        t,
        t,
      ],
    );
    return (await queryOne("SELECT * FROM bot_presets WHERE id = ?", [
      id,
    ])) as BotPresetRow;
  },

  /** Delete a preset the user owns (custom only). */
  async deleteOwned(id: string, userId: string): Promise<boolean> {
    const res = await execute(
      "DELETE FROM bot_presets WHERE id = ? AND owner_id = ? AND is_global = 0",
      [id, userId],
    );
    return res.rowCount > 0;
  },

  /** Admin: delete any preset (including global). */
  async deleteAny(id: string): Promise<boolean> {
    const res = await execute("DELETE FROM bot_presets WHERE id = ?", [id]);
    return res.rowCount > 0;
  },
};

export const botsRepo = {
  async create(input: {
    userId: string;
    name: string;
    mcUsername: string;
    serverHost: string;
    serverPort?: number;
    mcVersion?: string;
    authMode: BotRow["auth_mode"];
    accessToken?: string | null;
    ssid?: string | null;
    uuid?: string | null;
    authExpiresAt?: number | null;
    proxy?: string | null;
    message?: string | null;
    reply?: string | null;
    replyActions?: string | null;
    triggerKeyword?: string | null;
    webhookUrl?: string | null;
    messageInterval?: number | null;
    replyDelay?: number | null;
    replyCooldown?: number | null;
    afkInterval?: number | null;
    reconnectDelay?: number | null;
    inactivityTimeout?: number | null;
  }): Promise<BotRow> {
    const id = newId("bot");
    const t = now();
    await execute(
      `INSERT INTO bots
         (id, user_id, name, mc_username, server_host, server_port, mc_version,
          auth_mode, access_token, ssid, uuid, auth_expires_at, proxy,
          message, reply, reply_actions, trigger_keyword, webhook_url, message_interval,
          reply_delay, reply_cooldown, afk_interval, reconnect_delay,
          inactivity_timeout, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        id,
        input.userId,
        input.name,
        input.mcUsername,
        input.serverHost,
        input.serverPort ?? 25565,
        input.mcVersion ?? "1.21.1",
        input.authMode,
        input.accessToken ?? null,
        input.ssid ?? null,
        input.uuid ?? null,
        input.authExpiresAt ?? null,
        input.proxy ?? null,
        input.message ?? null,
        input.reply ?? null,
        input.replyActions ?? null,
        input.triggerKeyword ?? null,
        input.webhookUrl ?? null,
        input.messageInterval ?? null,
        input.replyDelay ?? null,
        input.replyCooldown ?? null,
        input.afkInterval ?? null,
        input.reconnectDelay ?? null,
        input.inactivityTimeout ?? null,
        t,
        t,
      ],
    );
    return (await queryOne("SELECT * FROM bots WHERE id = ?", [id])) as BotRow;
  },

  async update(
    id: string,
    userId: string,
    patch: Partial<{
      name: string;
      mc_username: string;
      server_host: string;
      server_port: number;
      mc_version: string;
      auth_mode: BotRow["auth_mode"];
      access_token: string | null;
      ssid: string | null;
      uuid: string | null;
      auth_expires_at: number | null;
      proxy: string | null;
      message: string | null;
      reply: string | null;
      reply_actions: string | null;
      trigger_keyword: string | null;
      webhook_url: string | null;
      message_interval: number | null;
      reply_delay: number | null;
      reply_cooldown: number | null;
      afk_interval: number | null;
      reconnect_delay: number | null;
      inactivity_timeout: number | null;
    }>,
  ): Promise<BotRow | undefined> {
    const current = await botsRepo.byIdForUser(id, userId);
    if (!current) return undefined;
    const pick = <K extends keyof BotRow>(k: K): BotRow[K] =>
      patch[k as keyof typeof patch] !== undefined
        ? (patch[k as keyof typeof patch] as BotRow[K])
        : current[k];
    const merged = {
      name: patch.name ?? current.name,
      mc_username: patch.mc_username ?? current.mc_username,
      server_host: patch.server_host ?? current.server_host,
      server_port: patch.server_port ?? current.server_port,
      mc_version: patch.mc_version ?? current.mc_version,
      auth_mode: patch.auth_mode ?? current.auth_mode,
      access_token:
        patch.access_token !== undefined ? patch.access_token : current.access_token,
      ssid: patch.ssid !== undefined ? patch.ssid : current.ssid,
      uuid: patch.uuid !== undefined ? patch.uuid : current.uuid,
      auth_expires_at:
        patch.auth_expires_at !== undefined
          ? patch.auth_expires_at
          : current.auth_expires_at,
      proxy: patch.proxy !== undefined ? patch.proxy : current.proxy,
      message: pick("message"),
      reply: pick("reply"),
      reply_actions: pick("reply_actions"),
      trigger_keyword: pick("trigger_keyword"),
      webhook_url: pick("webhook_url"),
      message_interval: pick("message_interval"),
      reply_delay: pick("reply_delay"),
      reply_cooldown: pick("reply_cooldown"),
      afk_interval: pick("afk_interval"),
      reconnect_delay: pick("reconnect_delay"),
      inactivity_timeout: pick("inactivity_timeout"),
    };
    await execute(
      `UPDATE bots SET name = ?, mc_username = ?, server_host = ?, server_port = ?,
         mc_version = ?, auth_mode = ?, access_token = ?, ssid = ?, uuid = ?,
         auth_expires_at = ?, proxy = ?, message = ?, reply = ?, reply_actions = ?,
         trigger_keyword = ?, webhook_url = ?, message_interval = ?,
         reply_delay = ?, reply_cooldown = ?, afk_interval = ?,
         reconnect_delay = ?, inactivity_timeout = ?,
         updated_at = ?
       WHERE id = ? AND user_id = ?`,
      [
        merged.name,
        merged.mc_username,
        merged.server_host,
        merged.server_port,
        merged.mc_version,
        merged.auth_mode,
        merged.access_token,
        merged.ssid,
        merged.uuid,
        merged.auth_expires_at,
        merged.proxy,
        merged.message,
        merged.reply,
        merged.reply_actions,
        merged.trigger_keyword,
        merged.webhook_url,
        merged.message_interval,
        merged.reply_delay,
        merged.reply_cooldown,
        merged.afk_interval,
        merged.reconnect_delay,
        merged.inactivity_timeout,
        now(),
        id,
        userId,
      ],
    );
    return botsRepo.byIdForUser(id, userId);
  },

  async forUser(userId: string): Promise<BotRow[]> {
    return (await query(
      "SELECT * FROM bots WHERE user_id = ? ORDER BY created_at DESC",
      [userId],
    )) as BotRow[];
  },

  async byIdForUser(id: string, userId: string): Promise<BotRow | undefined> {
    return (await queryOne("SELECT * FROM bots WHERE id = ? AND user_id = ?", [
      id,
      userId,
    ])) as BotRow | undefined;
  },

  async countForUser(userId: string): Promise<number> {
    return (
      (await queryOne("SELECT COUNT(*) AS c FROM bots WHERE user_id = ?", [
        userId,
      ])) as { c: number }
    ).c;
  },

  async delete(id: string, userId: string): Promise<void> {
    await execute("DELETE FROM bots WHERE id = ? AND user_id = ?", [id, userId]);
  },

  /**
   * Persist the in-game username the running bot detected from its
   * authenticated profile (Microsoft / SSID). Trusted system call (no user
   * scope) — invoked by the bot container via the runner identity callback —
   * so the website knows whose skin/bust to render. No-ops on an invalid name
   * or when it already matches what's stored.
   */
  async setDetectedUsername(id: string, username: string): Promise<void> {
    const clean = username.trim();
    if (!clean || !/^[A-Za-z0-9_]{1,16}$/.test(clean)) return;
    await execute(
      "UPDATE bots SET mc_username = ?, updated_at = ? WHERE id = ? AND mc_username <> ?",
      [clean, now(), id, clean],
    );
  },
};

export const botRunsRepo = {
  async create(input: { botId: string; userId: string }): Promise<BotRunRow> {
    const id = newId("brun");
    const t = now();
    await execute(
      `INSERT INTO bot_runs (id, bot_id, user_id, status, created_at, updated_at)
       VALUES (?, ?, ?, 'pending', ?, ?)`,
      [id, input.botId, input.userId, t, t],
    );
    return (await queryOne("SELECT * FROM bot_runs WHERE id = ?", [id])) as BotRunRow;
  },

  async activeForBot(botId: string): Promise<BotRunRow | undefined> {
    return (await queryOne(
      `SELECT * FROM bot_runs
         WHERE bot_id = ? AND status IN ('pending', 'starting', 'running')
         ORDER BY created_at DESC LIMIT 1`,
      [botId],
    )) as BotRunRow | undefined;
  },

  async latestForBot(botId: string): Promise<BotRunRow | undefined> {
    return (await queryOne(
      "SELECT * FROM bot_runs WHERE bot_id = ? ORDER BY created_at DESC LIMIT 1",
      [botId],
    )) as BotRunRow | undefined;
  },

  /** Latest run for every bot owned by a user, keyed by bot_id. */
  async latestForUser(userId: string): Promise<Record<string, BotRunRow>> {
    const rows = (await query(
      `SELECT DISTINCT ON (bot_id) *
         FROM bot_runs
         WHERE user_id = ?
         ORDER BY bot_id, created_at DESC`,
      [userId],
    )) as BotRunRow[];
    const map: Record<string, BotRunRow> = {};
    for (const r of rows) map[r.bot_id] = r;
    return map;
  },

  /** All active runs (pending/starting/running) for a user, latest first. */
  async activeForUser(userId: string): Promise<BotRunRow[]> {
    return (await query(
      `SELECT * FROM bot_runs
         WHERE user_id = ? AND status IN ('pending', 'starting', 'running')
         ORDER BY created_at ASC`,
      [userId],
    )) as BotRunRow[];
  },

  async byIdForUser(id: string, userId: string): Promise<BotRunRow | undefined> {
    return (await queryOne(
      "SELECT * FROM bot_runs WHERE id = ? AND user_id = ?",
      [id, userId],
    )) as BotRunRow | undefined;
  },

  async byId(id: string): Promise<BotRunRow | undefined> {
    return (await queryOne("SELECT * FROM bot_runs WHERE id = ?", [id])) as
      | BotRunRow
      | undefined;
  },

  async setStatus(
    id: string,
    status: BotRunRow["status"],
    extra?: { containerId?: string; error?: string },
  ): Promise<void> {
    const t = now();
    const stoppedAt = status === "stopped" || status === "error" ? t : null;
    await execute(
      `UPDATE bot_runs SET status = ?,
         container_id = COALESCE(?, container_id),
         error = COALESCE(?, error),
         updated_at = ?,
         stopped_at = COALESCE(?, stopped_at)
       WHERE id = ?`,
      [status, extra?.containerId ?? null, extra?.error ?? null, t, stoppedAt, id],
    );
  },

  async activeCount(): Promise<number> {
    return (
      (await queryOne(
        `SELECT COUNT(*) AS c FROM bot_runs WHERE status IN ('pending','starting','running')`,
        [],
      )) as { c: number }
    ).c;
  },

  /** All runs the orchestrator still considers live (pending/starting/running). */
  async activeRuns(): Promise<BotRunRow[]> {
    return (await query(
      `SELECT * FROM bot_runs WHERE status IN ('pending','starting','running') ORDER BY created_at ASC`,
      [],
    )) as BotRunRow[];
  },

  /**
   * Total milliseconds a user's bots have run so far during the current UTC
   * day. Counts the portion of each run that overlaps today; runs still active
   * are counted up to "now". Used to enforce the plan's daily bot-hours limit.
   */
  async usedMsToday(userId: string): Promise<number> {
    const nowMs = now();
    const dayStart = nowMs - (nowMs % 86_400_000); // UTC midnight
    const rows = (await query(
      `SELECT created_at, stopped_at FROM bot_runs
         WHERE user_id = ? AND status != 'error'
           AND (stopped_at IS NULL OR stopped_at >= ?)`,
      [userId, dayStart],
    )) as { created_at: number; stopped_at: number | null }[];
    let total = 0;
    for (const r of rows) {
      const start = Math.max(r.created_at, dayStart);
      const end = r.stopped_at ?? nowMs;
      if (end > start) total += end - start;
    }
    return total;
  },
};

// --- Redeem keys ------------------------------------------------------------

export interface RedeemKeyRow {
  id: string;
  code: string;
  type: "subscription" | "plugin";
  plan_id: string | null;
  plugin_id: string | null;
  duration_days: number | null;
  note: string | null;
  redeemed_by: string | null;
  redeemed_at: number | null;
  created_by: string;
  created_at: number;
}

function generateKeyCode(): string {
  const alphabet = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
  const group = () =>
    Array.from(
      { length: 4 },
      () => alphabet[Math.floor(Math.random() * alphabet.length)],
    ).join("");
  return `${group()}-${group()}-${group()}-${group()}`;
}

export const keysRepo = {
  async create(input: {
    type: "subscription" | "plugin";
    planId?: string | null;
    pluginId?: string | null;
    durationDays?: number | null;
    note?: string | null;
    createdBy: string;
  }): Promise<RedeemKeyRow> {
    const id = newId("key");
    // Retry a few times in the (astronomically unlikely) event of a collision.
    let code = generateKeyCode();
    for (let i = 0; i < 5; i++) {
      const exists = await queryOne("SELECT 1 FROM redeem_keys WHERE code = ?", [code]);
      if (!exists) break;
      code = generateKeyCode();
    }
    await execute(`INSERT INTO redeem_keys
         (id, code, type, plan_id, plugin_id, duration_days, note, created_by, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`, [id,
      code,
      input.type,
      input.planId ?? null,
      input.pluginId ?? null,
      input.durationDays ?? null,
      input.note ?? null,
      input.createdBy,
      now()]);
    return await queryOne("SELECT * FROM redeem_keys WHERE id = ?", [id]) as RedeemKeyRow;
  },

  async byCode(code: string): Promise<RedeemKeyRow | undefined> {
    return await queryOne("SELECT * FROM redeem_keys WHERE code = ?", [code]) as RedeemKeyRow | undefined;
  },

  async markRedeemed(id: string, userId: string): Promise<void> {
    await execute("UPDATE redeem_keys SET redeemed_by = ?, redeemed_at = ? WHERE id = ?", [userId, now(), id]);
  },

  async list(): Promise<RedeemKeyRow[]> {
    return await query("SELECT * FROM redeem_keys ORDER BY created_at DESC", []) as RedeemKeyRow[];
  },

  async delete(id: string): Promise<void> {
    await execute("DELETE FROM redeem_keys WHERE id = ?", [id]);
  },
};

// ---------------------------------------------------------------------------
// Global chat — shared messaging across all platform users.
// ---------------------------------------------------------------------------

export interface GlobalChatMessage {
  id: string;
  user_id: string;
  username: string;
  avatar_url: string | null;
  content: string;
  reply_to_id: string | null;
  reply_to_username: string | null;
  source: string;
  discord_message_id: string | null;
  created_at: number;
}

export const globalChatRepo = {
  async post(input: {
    userId: string;
    username: string;
    avatarUrl?: string | null;
    content: string;
    replyToId?: string | null;
    replyToUsername?: string | null;
    source?: "web" | "discord";
    discordMessageId?: string | null;
  }): Promise<GlobalChatMessage> {
    const id = newId("gcm");
    const t = now();
    const content = input.content.slice(0, 1000);
    const source = input.source ?? "web";
    await execute(
      `INSERT INTO global_chat_messages (id, user_id, username, avatar_url, content, reply_to_id, reply_to_username, source, discord_message_id, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [id, input.userId, input.username, input.avatarUrl ?? null, content, input.replyToId ?? null, input.replyToUsername ?? null, source, input.discordMessageId ?? null, t],
    );
    return { id, user_id: input.userId, username: input.username, avatar_url: input.avatarUrl ?? null, content, reply_to_id: input.replyToId ?? null, reply_to_username: input.replyToUsername ?? null, source, discord_message_id: input.discordMessageId ?? null, created_at: t };
  },

  async recent(limit = 100): Promise<GlobalChatMessage[]> {
    return await query<GlobalChatMessage>(
      `SELECT id, user_id, username, avatar_url, content, reply_to_id, reply_to_username, source, discord_message_id, created_at
       FROM global_chat_messages
       ORDER BY created_at DESC
       LIMIT ?`,
      [limit],
    );
  },

  async afterId(id: string, limit = 50): Promise<GlobalChatMessage[]> {
    const row = await queryOne<{ created_at: number }>(
      `SELECT created_at FROM global_chat_messages WHERE id = ?`,
      [id],
    );
    if (!row) return [];
    return await query<GlobalChatMessage>(
      `SELECT id, user_id, username, avatar_url, content, reply_to_id, reply_to_username, source, discord_message_id, created_at
       FROM global_chat_messages
       WHERE created_at > ?
       ORDER BY created_at ASC
       LIMIT ?`,
      [row.created_at, limit],
    );
  },

  async byId(id: string): Promise<GlobalChatMessage | undefined> {
    return await queryOne<GlobalChatMessage>(
      `SELECT id, user_id, username, avatar_url, content, reply_to_id, reply_to_username, source, discord_message_id, created_at
       FROM global_chat_messages WHERE id = ?`,
      [id],
    );
  },

  async deleteMessage(id: string): Promise<void> {
    await execute("DELETE FROM global_chat_messages WHERE id = ?", [id]);
  },

  async setTimeout(userId: string, durationMinutes: number): Promise<void> {
    const expiresAt = now() + durationMinutes * 60 * 1000;
    await execute(
      `INSERT INTO chat_timeouts (user_id, expires_at, reason, created_by, created_at)
       VALUES (?, ?, 'global chat', 'system', ?)
       ON CONFLICT (user_id) DO UPDATE SET
         expires_at = excluded.expires_at,
         reason = excluded.reason,
         created_by = excluded.created_by,
         created_at = excluded.created_at`,
      [userId, expiresAt, now()],
    );
  },

  async isTimedOut(userId: string): Promise<boolean> {
    const row = await queryOne<{ expires_at: number }>(
      `SELECT expires_at FROM chat_timeouts WHERE user_id = ?`,
      [userId],
    );
    if (!row) return false;
    return row.expires_at > now();
  },

  async deleteUserMessages(userId: string): Promise<void> {
    await execute("DELETE FROM global_chat_messages WHERE user_id = ?", [userId]);
  },
};

// ---------------------------------------------------------------------------
// User Webhooks — per-user Discord webhooks for sending as the user.
// ---------------------------------------------------------------------------

export interface UserWebhookRow {
  id: string;
  user_id: string;
  channel_id: string;
  webhook_url: string;
  webhook_token: string;
  created_at: number;
}

export const userWebhooksRepo = {
  async set(userId: string, channelId: string, webhookUrl: string, webhookToken: string): Promise<UserWebhookRow> {
    const id = newId("uwh");
    const t = now();
    await execute(
      `INSERT INTO user_webhooks (id, user_id, channel_id, webhook_url, webhook_token, created_at)
       VALUES (?, ?, ?, ?, ?, ?)
       ON CONFLICT (user_id, channel_id) DO UPDATE SET
         webhook_url = excluded.webhook_url,
         webhook_token = excluded.webhook_token,
         created_at = excluded.created_at`,
      [id, userId, channelId, webhookUrl, webhookToken, t],
    );
    return (await queryOne<UserWebhookRow>(
      "SELECT * FROM user_webhooks WHERE user_id = ? AND channel_id = ?",
      [userId, channelId],
    )) as UserWebhookRow;
  },

  async getForUser(userId: string): Promise<UserWebhookRow[]> {
    return await query<UserWebhookRow>(
      "SELECT * FROM user_webhooks WHERE user_id = ? ORDER BY created_at DESC",
      [userId],
    );
  },

  async getForChannel(channelId: string): Promise<UserWebhookRow | undefined> {
    return await queryOne<UserWebhookRow>(
      "SELECT * FROM user_webhooks WHERE channel_id = ? LIMIT 1",
      [channelId],
    );
  },

  async delete(userId: string, channelId: string): Promise<void> {
    await execute(
      "DELETE FROM user_webhooks WHERE user_id = ? AND channel_id = ?",
      [userId, channelId],
    );
  },
};

// ---------------------------------------------------------------------------
// Guild Chat — per-guild Discord bridge configuration.
// Bot token lives in env (server-side); webhook is auto-created per user-guild pair.
// ---------------------------------------------------------------------------

export interface GuildChatConfigRow {
  id: string;
  user_id: string;
  guild_id: string;
  guild_name: string | null;
  guild_icon: string | null;
  channel_id: string;
  channel_name: string | null;
  webhook_id: string | null;
  webhook_token: string | null;
  webhook_url: string | null;
  created_at: number;
  updated_at: number;
}

export const guildChatRepo = {
  async upsert(input: {
    userId: string;
    guildId: string;
    guildName?: string | null;
    guildIcon?: string | null;
    channelId: string;
    channelName?: string | null;
    webhookId: string;
    webhookToken: string;
    webhookUrl: string;
  }): Promise<GuildChatConfigRow> {
    const id = newId("gcc");
    const t = now();
    await execute(
      `INSERT INTO guild_chat_configs
         (id, user_id, guild_id, guild_name, guild_icon, channel_id, channel_name,
          webhook_id, webhook_token, webhook_url, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
       ON CONFLICT (user_id, guild_id) DO UPDATE SET
         guild_name   = excluded.guild_name,
         guild_icon   = excluded.guild_icon,
         channel_id   = excluded.channel_id,
         channel_name = excluded.channel_name,
         webhook_id   = excluded.webhook_id,
         webhook_token= excluded.webhook_token,
         webhook_url  = excluded.webhook_url,
         updated_at   = excluded.updated_at`,
      [id, input.userId, input.guildId, input.guildName ?? null,
       input.guildIcon ?? null, input.channelId, input.channelName ?? null,
       input.webhookId, input.webhookToken, input.webhookUrl, t, t],
    );
    return (await queryOne(
      "SELECT * FROM guild_chat_configs WHERE user_id = ? AND guild_id = ?",
      [input.userId, input.guildId],
    )) as GuildChatConfigRow;
  },

  async byUserId(userId: string): Promise<GuildChatConfigRow[]> {
    return await query(
      "SELECT * FROM guild_chat_configs WHERE user_id = ? ORDER BY created_at DESC",
      [userId],
    ) as GuildChatConfigRow[];
  },

  async byGuild(userId: string, guildId: string): Promise<GuildChatConfigRow | null> {
    return (await queryOne(
      "SELECT * FROM guild_chat_configs WHERE user_id = ? AND guild_id = ?",
      [userId, guildId],
    )) as GuildChatConfigRow | null;
  },

  async delete(userId: string, guildId: string): Promise<void> {
    await execute(
      "DELETE FROM guild_chat_configs WHERE user_id = ? AND guild_id = ?",
      [userId, guildId],
    );
  },
};

// Re-export helpers used by other server-side modules (e.g. bot/handlers.ts)
export { query, queryOne, execute };
