/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashRouteImport } from './routes/dash'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReviewsRouteImport } from './routes/api/reviews'
import { Route as ApiBotsRouteImport } from './routes/api/bots'
import { Route as ApiVpnCheckRouteImport } from './routes/api/vpn/check'
import { Route as ApiRunnerWorldRouteImport } from './routes/api/runner/world'
import { Route as ApiRunnerStreamRouteImport } from './routes/api/runner/stream'
import { Route as ApiRunnerPaymentsRouteImport } from './routes/api/runner/payments'
import { Route as ApiRunnerOutboxRouteImport } from './routes/api/runner/outbox'
import { Route as ApiRunnerLogsRouteImport } from './routes/api/runner/logs'
import { Route as ApiRunnerIdentityRouteImport } from './routes/api/runner/identity'
import { Route as ApiRunnerGlobalChatRouteImport } from './routes/api/runner/global-chat'
import { Route as ApiRunnerEventsRouteImport } from './routes/api/runner/events'
import { Route as ApiRunnerCaptchaRouteImport } from './routes/api/runner/captcha'
import { Route as ApiRunnerCallbackRouteImport } from './routes/api/runner/callback'
import { Route as ApiPaymentsCallbackRouteImport } from './routes/api/payments/callback'
import { Route as ApiGlobalChatSendRouteImport } from './routes/api/global-chat/send'
import { Route as ApiGlobalChatModerateRouteImport } from './routes/api/global-chat/moderate'
import { Route as ApiGlobalChatDeleteOwnRouteImport } from './routes/api/global-chat/delete-own'
import { Route as ApiGlobalChatBotSyncRouteImport } from './routes/api/global-chat/bot-sync'
import { Route as ApiBotsUpdateRouteImport } from './routes/api/bots/update'
import { Route as ApiBotsStopRouteImport } from './routes/api/bots/stop'
import { Route as ApiBotsStartRouteImport } from './routes/api/bots/start'
import { Route as ApiBotsDeleteRouteImport } from './routes/api/bots/delete'
import { Route as ApiBotsCreateRouteImport } from './routes/api/bots/create'
import { Route as ApiAuthKeyLoginRouteImport } from './routes/api/auth/key-login'
import { Route as ApiAuthDiscordRouteImport } from './routes/api/auth/discord'
import { Route as ApiAiGenerateActionsRouteImport } from './routes/api/ai/generate-actions'
import { Route as ApiGuildChatSendRouteImport } from './routes/api/guild/chat/send'
import { Route as ApiGuildChatMessagesRouteImport } from './routes/api/guild/chat/messages'
import { Route as ApiGuildChatMembersRouteImport } from './routes/api/guild/chat/members'
import { Route as ApiGuildChatGuildsRouteImport } from './routes/api/guild/chat/guilds'
import { Route as ApiGuildChatConfigRouteImport } from './routes/api/guild/chat/config'
import { Route as ApiGuildChatChannelsRouteImport } from './routes/api/guild/chat/channels'
import { Route as ApiAuthDiscordCallbackRouteImport } from './routes/api/auth/discord.callback'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsRoute = ApiReviewsRouteImport.update({
  id: '/api/reviews',
  path: '/api/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsRoute = ApiBotsRouteImport.update({
  id: '/api/bots',
  path: '/api/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVpnCheckRoute = ApiVpnCheckRouteImport.update({
  id: '/api/vpn/check',
  path: '/api/vpn/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunnerWorldRoute = ApiRunnerWorldRouteImport.update({
  id: '/api/runner/world',
  path: '/api/runner/world',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunnerStreamRoute = ApiRunnerStreamRouteImport.update({
  id: '/api/runner/stream',
  path: '/api/runner/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunnerPaymentsRoute = ApiRunnerPaymentsRouteImport.update({
  id: '/api/runner/payments',
  path: '/api/runner/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunnerOutboxRoute = ApiRunnerOutboxRouteImport.update({
  id: '/api/runner/outbox',
  path: '/api/runner/outbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunnerLogsRoute = ApiRunnerLogsRouteImport.update({
  id: '/api/runner/logs',
  path: '/api/runner/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunnerIdentityRoute = ApiRunnerIdentityRouteImport.update({
  id: '/api/runner/identity',
  path: '/api/runner/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunnerGlobalChatRoute = ApiRunnerGlobalChatRouteImport.update({
  id: '/api/runner/global-chat',
  path: '/api/runner/global-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunnerEventsRoute = ApiRunnerEventsRouteImport.update({
  id: '/api/runner/events',
  path: '/api/runner/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunnerCaptchaRoute = ApiRunnerCaptchaRouteImport.update({
  id: '/api/runner/captcha',
  path: '/api/runner/captcha',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunnerCallbackRoute = ApiRunnerCallbackRouteImport.update({
  id: '/api/runner/callback',
  path: '/api/runner/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCallbackRoute = ApiPaymentsCallbackRouteImport.update({
  id: '/api/payments/callback',
  path: '/api/payments/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGlobalChatSendRoute = ApiGlobalChatSendRouteImport.update({
  id: '/api/global-chat/send',
  path: '/api/global-chat/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGlobalChatModerateRoute = ApiGlobalChatModerateRouteImport.update({
  id: '/api/global-chat/moderate',
  path: '/api/global-chat/moderate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGlobalChatDeleteOwnRoute = ApiGlobalChatDeleteOwnRouteImport.update({
  id: '/api/global-chat/delete-own',
  path: '/api/global-chat/delete-own',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGlobalChatBotSyncRoute = ApiGlobalChatBotSyncRouteImport.update({
  id: '/api/global-chat/bot-sync',
  path: '/api/global-chat/bot-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotsUpdateRoute = ApiBotsUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => ApiBotsRoute,
} as any)
const ApiBotsStopRoute = ApiBotsStopRouteImport.update({
  id: '/stop',
  path: '/stop',
  getParentRoute: () => ApiBotsRoute,
} as any)
const ApiBotsStartRoute = ApiBotsStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => ApiBotsRoute,
} as any)
const ApiBotsDeleteRoute = ApiBotsDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => ApiBotsRoute,
} as any)
const ApiBotsCreateRoute = ApiBotsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ApiBotsRoute,
} as any)
const ApiAuthKeyLoginRoute = ApiAuthKeyLoginRouteImport.update({
  id: '/api/auth/key-login',
  path: '/api/auth/key-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordRoute = ApiAuthDiscordRouteImport.update({
  id: '/api/auth/discord',
  path: '/api/auth/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateActionsRoute = ApiAiGenerateActionsRouteImport.update({
  id: '/api/ai/generate-actions',
  path: '/api/ai/generate-actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuildChatSendRoute = ApiGuildChatSendRouteImport.update({
  id: '/api/guild/chat/send',
  path: '/api/guild/chat/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuildChatMessagesRoute = ApiGuildChatMessagesRouteImport.update({
  id: '/api/guild/chat/messages',
  path: '/api/guild/chat/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuildChatMembersRoute = ApiGuildChatMembersRouteImport.update({
  id: '/api/guild/chat/members',
  path: '/api/guild/chat/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuildChatGuildsRoute = ApiGuildChatGuildsRouteImport.update({
  id: '/api/guild/chat/guilds',
  path: '/api/guild/chat/guilds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuildChatConfigRoute = ApiGuildChatConfigRouteImport.update({
  id: '/api/guild/chat/config',
  path: '/api/guild/chat/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuildChatChannelsRoute = ApiGuildChatChannelsRouteImport.update({
  id: '/api/guild/chat/channels',
  path: '/api/guild/chat/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordCallbackRoute = ApiAuthDiscordCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthDiscordRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blocked': typeof BlockedRoute
  '/changelog': typeof ChangelogRoute
  '/dash': typeof DashRoute
  '/docs': typeof DocsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/api/bots': typeof ApiBotsRouteWithChildren
  '/api/reviews': typeof ApiReviewsRoute
  '/api/ai/generate-actions': typeof ApiAiGenerateActionsRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/key-login': typeof ApiAuthKeyLoginRoute
  '/api/bots/create': typeof ApiBotsCreateRoute
  '/api/bots/delete': typeof ApiBotsDeleteRoute
  '/api/bots/start': typeof ApiBotsStartRoute
  '/api/bots/stop': typeof ApiBotsStopRoute
  '/api/bots/update': typeof ApiBotsUpdateRoute
  '/api/global-chat/bot-sync': typeof ApiGlobalChatBotSyncRoute
  '/api/global-chat/delete-own': typeof ApiGlobalChatDeleteOwnRoute
  '/api/global-chat/moderate': typeof ApiGlobalChatModerateRoute
  '/api/global-chat/send': typeof ApiGlobalChatSendRoute
  '/api/payments/callback': typeof ApiPaymentsCallbackRoute
  '/api/runner/callback': typeof ApiRunnerCallbackRoute
  '/api/runner/captcha': typeof ApiRunnerCaptchaRoute
  '/api/runner/events': typeof ApiRunnerEventsRoute
  '/api/runner/global-chat': typeof ApiRunnerGlobalChatRoute
  '/api/runner/identity': typeof ApiRunnerIdentityRoute
  '/api/runner/logs': typeof ApiRunnerLogsRoute
  '/api/runner/outbox': typeof ApiRunnerOutboxRoute
  '/api/runner/payments': typeof ApiRunnerPaymentsRoute
  '/api/runner/stream': typeof ApiRunnerStreamRoute
  '/api/runner/world': typeof ApiRunnerWorldRoute
  '/api/vpn/check': typeof ApiVpnCheckRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/guild/chat/channels': typeof ApiGuildChatChannelsRoute
  '/api/guild/chat/config': typeof ApiGuildChatConfigRoute
  '/api/guild/chat/guilds': typeof ApiGuildChatGuildsRoute
  '/api/guild/chat/members': typeof ApiGuildChatMembersRoute
  '/api/guild/chat/messages': typeof ApiGuildChatMessagesRoute
  '/api/guild/chat/send': typeof ApiGuildChatSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blocked': typeof BlockedRoute
  '/changelog': typeof ChangelogRoute
  '/dash': typeof DashRoute
  '/docs': typeof DocsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/api/bots': typeof ApiBotsRouteWithChildren
  '/api/reviews': typeof ApiReviewsRoute
  '/api/ai/generate-actions': typeof ApiAiGenerateActionsRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/key-login': typeof ApiAuthKeyLoginRoute
  '/api/bots/create': typeof ApiBotsCreateRoute
  '/api/bots/delete': typeof ApiBotsDeleteRoute
  '/api/bots/start': typeof ApiBotsStartRoute
  '/api/bots/stop': typeof ApiBotsStopRoute
  '/api/bots/update': typeof ApiBotsUpdateRoute
  '/api/global-chat/bot-sync': typeof ApiGlobalChatBotSyncRoute
  '/api/global-chat/delete-own': typeof ApiGlobalChatDeleteOwnRoute
  '/api/global-chat/moderate': typeof ApiGlobalChatModerateRoute
  '/api/global-chat/send': typeof ApiGlobalChatSendRoute
  '/api/payments/callback': typeof ApiPaymentsCallbackRoute
  '/api/runner/callback': typeof ApiRunnerCallbackRoute
  '/api/runner/captcha': typeof ApiRunnerCaptchaRoute
  '/api/runner/events': typeof ApiRunnerEventsRoute
  '/api/runner/global-chat': typeof ApiRunnerGlobalChatRoute
  '/api/runner/identity': typeof ApiRunnerIdentityRoute
  '/api/runner/logs': typeof ApiRunnerLogsRoute
  '/api/runner/outbox': typeof ApiRunnerOutboxRoute
  '/api/runner/payments': typeof ApiRunnerPaymentsRoute
  '/api/runner/stream': typeof ApiRunnerStreamRoute
  '/api/runner/world': typeof ApiRunnerWorldRoute
  '/api/vpn/check': typeof ApiVpnCheckRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/guild/chat/channels': typeof ApiGuildChatChannelsRoute
  '/api/guild/chat/config': typeof ApiGuildChatConfigRoute
  '/api/guild/chat/guilds': typeof ApiGuildChatGuildsRoute
  '/api/guild/chat/members': typeof ApiGuildChatMembersRoute
  '/api/guild/chat/messages': typeof ApiGuildChatMessagesRoute
  '/api/guild/chat/send': typeof ApiGuildChatSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blocked': typeof BlockedRoute
  '/changelog': typeof ChangelogRoute
  '/dash': typeof DashRoute
  '/docs': typeof DocsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/terms': typeof TermsRoute
  '/api/bots': typeof ApiBotsRouteWithChildren
  '/api/reviews': typeof ApiReviewsRoute
  '/api/ai/generate-actions': typeof ApiAiGenerateActionsRoute
  '/api/auth/discord': typeof ApiAuthDiscordRouteWithChildren
  '/api/auth/key-login': typeof ApiAuthKeyLoginRoute
  '/api/bots/create': typeof ApiBotsCreateRoute
  '/api/bots/delete': typeof ApiBotsDeleteRoute
  '/api/bots/start': typeof ApiBotsStartRoute
  '/api/bots/stop': typeof ApiBotsStopRoute
  '/api/bots/update': typeof ApiBotsUpdateRoute
  '/api/global-chat/bot-sync': typeof ApiGlobalChatBotSyncRoute
  '/api/global-chat/delete-own': typeof ApiGlobalChatDeleteOwnRoute
  '/api/global-chat/moderate': typeof ApiGlobalChatModerateRoute
  '/api/global-chat/send': typeof ApiGlobalChatSendRoute
  '/api/payments/callback': typeof ApiPaymentsCallbackRoute
  '/api/runner/callback': typeof ApiRunnerCallbackRoute
  '/api/runner/captcha': typeof ApiRunnerCaptchaRoute
  '/api/runner/events': typeof ApiRunnerEventsRoute
  '/api/runner/global-chat': typeof ApiRunnerGlobalChatRoute
  '/api/runner/identity': typeof ApiRunnerIdentityRoute
  '/api/runner/logs': typeof ApiRunnerLogsRoute
  '/api/runner/outbox': typeof ApiRunnerOutboxRoute
  '/api/runner/payments': typeof ApiRunnerPaymentsRoute
  '/api/runner/stream': typeof ApiRunnerStreamRoute
  '/api/runner/world': typeof ApiRunnerWorldRoute
  '/api/vpn/check': typeof ApiVpnCheckRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/guild/chat/channels': typeof ApiGuildChatChannelsRoute
  '/api/guild/chat/config': typeof ApiGuildChatConfigRoute
  '/api/guild/chat/guilds': typeof ApiGuildChatGuildsRoute
  '/api/guild/chat/members': typeof ApiGuildChatMembersRoute
  '/api/guild/chat/messages': typeof ApiGuildChatMessagesRoute
  '/api/guild/chat/send': typeof ApiGuildChatSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blocked'
    | '/changelog'
    | '/dash'
    | '/docs'
    | '/leaderboard'
    | '/login'
    | '/maintenance'
    | '/pricing'
    | '/reviews'
    | '/terms'
    | '/api/bots'
    | '/api/reviews'
    | '/api/ai/generate-actions'
    | '/api/auth/discord'
    | '/api/auth/key-login'
    | '/api/bots/create'
    | '/api/bots/delete'
    | '/api/bots/start'
    | '/api/bots/stop'
    | '/api/bots/update'
    | '/api/global-chat/bot-sync'
    | '/api/global-chat/delete-own'
    | '/api/global-chat/moderate'
    | '/api/global-chat/send'
    | '/api/payments/callback'
    | '/api/runner/callback'
    | '/api/runner/captcha'
    | '/api/runner/events'
    | '/api/runner/global-chat'
    | '/api/runner/identity'
    | '/api/runner/logs'
    | '/api/runner/outbox'
    | '/api/runner/payments'
    | '/api/runner/stream'
    | '/api/runner/world'
    | '/api/vpn/check'
    | '/api/auth/discord/callback'
    | '/api/guild/chat/channels'
    | '/api/guild/chat/config'
    | '/api/guild/chat/guilds'
    | '/api/guild/chat/members'
    | '/api/guild/chat/messages'
    | '/api/guild/chat/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blocked'
    | '/changelog'
    | '/dash'
    | '/docs'
    | '/leaderboard'
    | '/login'
    | '/maintenance'
    | '/pricing'
    | '/reviews'
    | '/terms'
    | '/api/bots'
    | '/api/reviews'
    | '/api/ai/generate-actions'
    | '/api/auth/discord'
    | '/api/auth/key-login'
    | '/api/bots/create'
    | '/api/bots/delete'
    | '/api/bots/start'
    | '/api/bots/stop'
    | '/api/bots/update'
    | '/api/global-chat/bot-sync'
    | '/api/global-chat/delete-own'
    | '/api/global-chat/moderate'
    | '/api/global-chat/send'
    | '/api/payments/callback'
    | '/api/runner/callback'
    | '/api/runner/captcha'
    | '/api/runner/events'
    | '/api/runner/global-chat'
    | '/api/runner/identity'
    | '/api/runner/logs'
    | '/api/runner/outbox'
    | '/api/runner/payments'
    | '/api/runner/stream'
    | '/api/runner/world'
    | '/api/vpn/check'
    | '/api/auth/discord/callback'
    | '/api/guild/chat/channels'
    | '/api/guild/chat/config'
    | '/api/guild/chat/guilds'
    | '/api/guild/chat/members'
    | '/api/guild/chat/messages'
    | '/api/guild/chat/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blocked'
    | '/changelog'
    | '/dash'
    | '/docs'
    | '/leaderboard'
    | '/login'
    | '/maintenance'
    | '/pricing'
    | '/reviews'
    | '/terms'
    | '/api/bots'
    | '/api/reviews'
    | '/api/ai/generate-actions'
    | '/api/auth/discord'
    | '/api/auth/key-login'
    | '/api/bots/create'
    | '/api/bots/delete'
    | '/api/bots/start'
    | '/api/bots/stop'
    | '/api/bots/update'
    | '/api/global-chat/bot-sync'
    | '/api/global-chat/delete-own'
    | '/api/global-chat/moderate'
    | '/api/global-chat/send'
    | '/api/payments/callback'
    | '/api/runner/callback'
    | '/api/runner/captcha'
    | '/api/runner/events'
    | '/api/runner/global-chat'
    | '/api/runner/identity'
    | '/api/runner/logs'
    | '/api/runner/outbox'
    | '/api/runner/payments'
    | '/api/runner/stream'
    | '/api/runner/world'
    | '/api/vpn/check'
    | '/api/auth/discord/callback'
    | '/api/guild/chat/channels'
    | '/api/guild/chat/config'
    | '/api/guild/chat/guilds'
    | '/api/guild/chat/members'
    | '/api/guild/chat/messages'
    | '/api/guild/chat/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlockedRoute: typeof BlockedRoute
  ChangelogRoute: typeof ChangelogRoute
  DashRoute: typeof DashRoute
  DocsRoute: typeof DocsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PricingRoute: typeof PricingRoute
  ReviewsRoute: typeof ReviewsRoute
  TermsRoute: typeof TermsRoute
  ApiBotsRoute: typeof ApiBotsRouteWithChildren
  ApiReviewsRoute: typeof ApiReviewsRoute
  ApiAiGenerateActionsRoute: typeof ApiAiGenerateActionsRoute
  ApiAuthDiscordRoute: typeof ApiAuthDiscordRouteWithChildren
  ApiAuthKeyLoginRoute: typeof ApiAuthKeyLoginRoute
  ApiGlobalChatBotSyncRoute: typeof ApiGlobalChatBotSyncRoute
  ApiGlobalChatDeleteOwnRoute: typeof ApiGlobalChatDeleteOwnRoute
  ApiGlobalChatModerateRoute: typeof ApiGlobalChatModerateRoute
  ApiGlobalChatSendRoute: typeof ApiGlobalChatSendRoute
  ApiPaymentsCallbackRoute: typeof ApiPaymentsCallbackRoute
  ApiRunnerCallbackRoute: typeof ApiRunnerCallbackRoute
  ApiRunnerCaptchaRoute: typeof ApiRunnerCaptchaRoute
  ApiRunnerEventsRoute: typeof ApiRunnerEventsRoute
  ApiRunnerGlobalChatRoute: typeof ApiRunnerGlobalChatRoute
  ApiRunnerIdentityRoute: typeof ApiRunnerIdentityRoute
  ApiRunnerLogsRoute: typeof ApiRunnerLogsRoute
  ApiRunnerOutboxRoute: typeof ApiRunnerOutboxRoute
  ApiRunnerPaymentsRoute: typeof ApiRunnerPaymentsRoute
  ApiRunnerStreamRoute: typeof ApiRunnerStreamRoute
  ApiRunnerWorldRoute: typeof ApiRunnerWorldRoute
  ApiVpnCheckRoute: typeof ApiVpnCheckRoute
  ApiGuildChatChannelsRoute: typeof ApiGuildChatChannelsRoute
  ApiGuildChatConfigRoute: typeof ApiGuildChatConfigRoute
  ApiGuildChatGuildsRoute: typeof ApiGuildChatGuildsRoute
  ApiGuildChatMembersRoute: typeof ApiGuildChatMembersRoute
  ApiGuildChatMessagesRoute: typeof ApiGuildChatMessagesRoute
  ApiGuildChatSendRoute: typeof ApiGuildChatSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews': {
      id: '/api/reviews'
      path: '/api/reviews'
      fullPath: '/api/reviews'
      preLoaderRoute: typeof ApiReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots': {
      id: '/api/bots'
      path: '/api/bots'
      fullPath: '/api/bots'
      preLoaderRoute: typeof ApiBotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vpn/check': {
      id: '/api/vpn/check'
      path: '/api/vpn/check'
      fullPath: '/api/vpn/check'
      preLoaderRoute: typeof ApiVpnCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runner/world': {
      id: '/api/runner/world'
      path: '/api/runner/world'
      fullPath: '/api/runner/world'
      preLoaderRoute: typeof ApiRunnerWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runner/stream': {
      id: '/api/runner/stream'
      path: '/api/runner/stream'
      fullPath: '/api/runner/stream'
      preLoaderRoute: typeof ApiRunnerStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runner/payments': {
      id: '/api/runner/payments'
      path: '/api/runner/payments'
      fullPath: '/api/runner/payments'
      preLoaderRoute: typeof ApiRunnerPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runner/outbox': {
      id: '/api/runner/outbox'
      path: '/api/runner/outbox'
      fullPath: '/api/runner/outbox'
      preLoaderRoute: typeof ApiRunnerOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runner/logs': {
      id: '/api/runner/logs'
      path: '/api/runner/logs'
      fullPath: '/api/runner/logs'
      preLoaderRoute: typeof ApiRunnerLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runner/identity': {
      id: '/api/runner/identity'
      path: '/api/runner/identity'
      fullPath: '/api/runner/identity'
      preLoaderRoute: typeof ApiRunnerIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runner/global-chat': {
      id: '/api/runner/global-chat'
      path: '/api/runner/global-chat'
      fullPath: '/api/runner/global-chat'
      preLoaderRoute: typeof ApiRunnerGlobalChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runner/events': {
      id: '/api/runner/events'
      path: '/api/runner/events'
      fullPath: '/api/runner/events'
      preLoaderRoute: typeof ApiRunnerEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runner/captcha': {
      id: '/api/runner/captcha'
      path: '/api/runner/captcha'
      fullPath: '/api/runner/captcha'
      preLoaderRoute: typeof ApiRunnerCaptchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runner/callback': {
      id: '/api/runner/callback'
      path: '/api/runner/callback'
      fullPath: '/api/runner/callback'
      preLoaderRoute: typeof ApiRunnerCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/callback': {
      id: '/api/payments/callback'
      path: '/api/payments/callback'
      fullPath: '/api/payments/callback'
      preLoaderRoute: typeof ApiPaymentsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/global-chat/send': {
      id: '/api/global-chat/send'
      path: '/api/global-chat/send'
      fullPath: '/api/global-chat/send'
      preLoaderRoute: typeof ApiGlobalChatSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/global-chat/moderate': {
      id: '/api/global-chat/moderate'
      path: '/api/global-chat/moderate'
      fullPath: '/api/global-chat/moderate'
      preLoaderRoute: typeof ApiGlobalChatModerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/global-chat/delete-own': {
      id: '/api/global-chat/delete-own'
      path: '/api/global-chat/delete-own'
      fullPath: '/api/global-chat/delete-own'
      preLoaderRoute: typeof ApiGlobalChatDeleteOwnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/global-chat/bot-sync': {
      id: '/api/global-chat/bot-sync'
      path: '/api/global-chat/bot-sync'
      fullPath: '/api/global-chat/bot-sync'
      preLoaderRoute: typeof ApiGlobalChatBotSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bots/update': {
      id: '/api/bots/update'
      path: '/update'
      fullPath: '/api/bots/update'
      preLoaderRoute: typeof ApiBotsUpdateRouteImport
      parentRoute: typeof ApiBotsRoute
    }
    '/api/bots/stop': {
      id: '/api/bots/stop'
      path: '/stop'
      fullPath: '/api/bots/stop'
      preLoaderRoute: typeof ApiBotsStopRouteImport
      parentRoute: typeof ApiBotsRoute
    }
    '/api/bots/start': {
      id: '/api/bots/start'
      path: '/start'
      fullPath: '/api/bots/start'
      preLoaderRoute: typeof ApiBotsStartRouteImport
      parentRoute: typeof ApiBotsRoute
    }
    '/api/bots/delete': {
      id: '/api/bots/delete'
      path: '/delete'
      fullPath: '/api/bots/delete'
      preLoaderRoute: typeof ApiBotsDeleteRouteImport
      parentRoute: typeof ApiBotsRoute
    }
    '/api/bots/create': {
      id: '/api/bots/create'
      path: '/create'
      fullPath: '/api/bots/create'
      preLoaderRoute: typeof ApiBotsCreateRouteImport
      parentRoute: typeof ApiBotsRoute
    }
    '/api/auth/key-login': {
      id: '/api/auth/key-login'
      path: '/api/auth/key-login'
      fullPath: '/api/auth/key-login'
      preLoaderRoute: typeof ApiAuthKeyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord': {
      id: '/api/auth/discord'
      path: '/api/auth/discord'
      fullPath: '/api/auth/discord'
      preLoaderRoute: typeof ApiAuthDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-actions': {
      id: '/api/ai/generate-actions'
      path: '/api/ai/generate-actions'
      fullPath: '/api/ai/generate-actions'
      preLoaderRoute: typeof ApiAiGenerateActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guild/chat/send': {
      id: '/api/guild/chat/send'
      path: '/api/guild/chat/send'
      fullPath: '/api/guild/chat/send'
      preLoaderRoute: typeof ApiGuildChatSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guild/chat/messages': {
      id: '/api/guild/chat/messages'
      path: '/api/guild/chat/messages'
      fullPath: '/api/guild/chat/messages'
      preLoaderRoute: typeof ApiGuildChatMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guild/chat/members': {
      id: '/api/guild/chat/members'
      path: '/api/guild/chat/members'
      fullPath: '/api/guild/chat/members'
      preLoaderRoute: typeof ApiGuildChatMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guild/chat/guilds': {
      id: '/api/guild/chat/guilds'
      path: '/api/guild/chat/guilds'
      fullPath: '/api/guild/chat/guilds'
      preLoaderRoute: typeof ApiGuildChatGuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guild/chat/config': {
      id: '/api/guild/chat/config'
      path: '/api/guild/chat/config'
      fullPath: '/api/guild/chat/config'
      preLoaderRoute: typeof ApiGuildChatConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guild/chat/channels': {
      id: '/api/guild/chat/channels'
      path: '/api/guild/chat/channels'
      fullPath: '/api/guild/chat/channels'
      preLoaderRoute: typeof ApiGuildChatChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/callback': {
      id: '/api/auth/discord/callback'
      path: '/callback'
      fullPath: '/api/auth/discord/callback'
      preLoaderRoute: typeof ApiAuthDiscordCallbackRouteImport
      parentRoute: typeof ApiAuthDiscordRoute
    }
  }
}

interface ApiBotsRouteChildren {
  ApiBotsCreateRoute: typeof ApiBotsCreateRoute
  ApiBotsDeleteRoute: typeof ApiBotsDeleteRoute
  ApiBotsStartRoute: typeof ApiBotsStartRoute
  ApiBotsStopRoute: typeof ApiBotsStopRoute
  ApiBotsUpdateRoute: typeof ApiBotsUpdateRoute
}

const ApiBotsRouteChildren: ApiBotsRouteChildren = {
  ApiBotsCreateRoute: ApiBotsCreateRoute,
  ApiBotsDeleteRoute: ApiBotsDeleteRoute,
  ApiBotsStartRoute: ApiBotsStartRoute,
  ApiBotsStopRoute: ApiBotsStopRoute,
  ApiBotsUpdateRoute: ApiBotsUpdateRoute,
}

const ApiBotsRouteWithChildren =
  ApiBotsRoute._addFileChildren(ApiBotsRouteChildren)

interface ApiAuthDiscordRouteChildren {
  ApiAuthDiscordCallbackRoute: typeof ApiAuthDiscordCallbackRoute
}

const ApiAuthDiscordRouteChildren: ApiAuthDiscordRouteChildren = {
  ApiAuthDiscordCallbackRoute: ApiAuthDiscordCallbackRoute,
}

const ApiAuthDiscordRouteWithChildren = ApiAuthDiscordRoute._addFileChildren(
  ApiAuthDiscordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlockedRoute: BlockedRoute,
  ChangelogRoute: ChangelogRoute,
  DashRoute: DashRoute,
  DocsRoute: DocsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  PricingRoute: PricingRoute,
  ReviewsRoute: ReviewsRoute,
  TermsRoute: TermsRoute,
  ApiBotsRoute: ApiBotsRouteWithChildren,
  ApiReviewsRoute: ApiReviewsRoute,
  ApiAiGenerateActionsRoute: ApiAiGenerateActionsRoute,
  ApiAuthDiscordRoute: ApiAuthDiscordRouteWithChildren,
  ApiAuthKeyLoginRoute: ApiAuthKeyLoginRoute,
  ApiGlobalChatBotSyncRoute: ApiGlobalChatBotSyncRoute,
  ApiGlobalChatDeleteOwnRoute: ApiGlobalChatDeleteOwnRoute,
  ApiGlobalChatModerateRoute: ApiGlobalChatModerateRoute,
  ApiGlobalChatSendRoute: ApiGlobalChatSendRoute,
  ApiPaymentsCallbackRoute: ApiPaymentsCallbackRoute,
  ApiRunnerCallbackRoute: ApiRunnerCallbackRoute,
  ApiRunnerCaptchaRoute: ApiRunnerCaptchaRoute,
  ApiRunnerEventsRoute: ApiRunnerEventsRoute,
  ApiRunnerGlobalChatRoute: ApiRunnerGlobalChatRoute,
  ApiRunnerIdentityRoute: ApiRunnerIdentityRoute,
  ApiRunnerLogsRoute: ApiRunnerLogsRoute,
  ApiRunnerOutboxRoute: ApiRunnerOutboxRoute,
  ApiRunnerPaymentsRoute: ApiRunnerPaymentsRoute,
  ApiRunnerStreamRoute: ApiRunnerStreamRoute,
  ApiRunnerWorldRoute: ApiRunnerWorldRoute,
  ApiVpnCheckRoute: ApiVpnCheckRoute,
  ApiGuildChatChannelsRoute: ApiGuildChatChannelsRoute,
  ApiGuildChatConfigRoute: ApiGuildChatConfigRoute,
  ApiGuildChatGuildsRoute: ApiGuildChatGuildsRoute,
  ApiGuildChatMembersRoute: ApiGuildChatMembersRoute,
  ApiGuildChatMessagesRoute: ApiGuildChatMessagesRoute,
  ApiGuildChatSendRoute: ApiGuildChatSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
